### ISSUE TITLE
Upgrade Eclipse Temurin base image Java version 21

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-tractusx/tractusx-edc#1002]
## WHAT

Update eclipse-temuring base image Java version to 21.

## WHY

Java is a living creature that is released every 6 months, with an LTS every 2 years, we should at least try to stay updated with the latest LTS.

## HOW

just switch 17 to 21

## FURTHER NOTES

// anything else you want to outline

_Please be sure to take a look at
our [contribution guidelines](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/CONTRIBUTING.md) and
our [PR etiquette](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/pr_etiquette.md)._

**Comment by wolf4ood** [comment]
closed by https://github.com/eclipse-tractusx/tractusx-edc/pull/1001
