### ISSUE TITLE
Inconsistent JSON structure when requesting catalog

### ISSUE THREAD

**Issue by anschl** [eclipse-tractusx/tractusx-edc#1016]
## Describe the bug

In the response JSON structure `dcat:dataset` is an object if one entry was returned and an array otherwise.

### To Reproduce

1. Set up empty EDC Connectors
2. Request the catalog:
```bash
curl --location 'http://localhost/bob/management/v2/catalog/request' \
--header 'Content-Type: application/json' \
--header 'X-Api-Key: password' \
--data-raw '{
  "@context": {
    "edc": "https://w3id.org/edc/v0.0.1/ns/"
  },
  "@type": "CatalogRequest",
  "counterPartyAddress": "http://alice-controlplane:8084/api/v1/dsp",
  "protocol": "dataspace-protocol-http",
  "querySpec": {
    "offset": 0,
    "limit": 50
  }
}'
```
3. Inspect the response:
```json
{
  "@id": "7c548a2f-9f7a-414f-91b1-5082347105a2",
  "@type": "dcat:Catalog",
  "dcat:dataset": [],
  ...
}
```
4. Add an asset
5. Inspect the response and compare `dcat:dataset`:
```json
{
  "@id": "43a6e096-8b81-46c4-b5e3-ba96e74fce23",
  "@type": "dcat:Catalog",
  "dcat:dataset": {
    "@id": "3",
    "@type": "dcat:Dataset",
  ...
}
```
6. Add a second asset
7. Inspect the response and compare `dcat:dataset`:
```json
{
  "@id": "6581a1ce-1f34-4d77-bd17-de673befaf67",
  "@type": "dcat:Catalog",
  "dcat:dataset": [
    {
      "@id": "3",
      "@type": "dcat:Dataset",
  ...
}
```

### Expected behavior

I expect the API to always return an array to stay consistent.

## Context Information

The image I'm using:
docker.io/tractusx/edc-controlplane-postgresql-hashicorp-vault@sha256:505788e0f063c0f2127bd6469a6659bb252210e32561dbff07552a9fea3d6c6b

I'm following this tutorial:
https://github.com/eclipse-tractusx/tutorial-resources/tree/main/mxd

**Comment by neischlah** [comment]
I see, thank you! Feel free to close the issue then.
