### ISSUE TITLE
Policy `profile` field ignored

### ISSUE THREAD

**Issue by matgnt** [eclipse-tractusx/tractusx-edc#1099]
For 2405 we'll introduce an ODRL profile as described here:
https://www.w3.org/TR/odrl-model/#profile

For this, we need a Policy to be able to handle the `profile` property as described here:
https://www.w3.org/TR/odrl-model/#policy
```
A Policy MAY have none, one, or many profile property values (of type IRI [[rfc3987](https://www.w3.org/TR/odrl-model/#bib-rfc3987)]) to identify the ODRL Profile that this Policy conforms to. (See the [ODRL Profiles](https://www.w3.org/TR/odrl-model/#profile) section for more details.)
```

It seems in 0.5.3 this field gets ignored. It's not stored in the database when a policy is created. It also does not report any error.

**Comment by jimmarino** [comment]
Closing because this issue is with EDC, not Tractus-X, and has been filed there.
