### ISSUE TITLE
Add `cx-policy` to the default context

### ISSUE THREAD

**Issue by matgnt** [eclipse-tractusx/tractusx-edc#1100]
We'll have a new namespace for legal definitions of parts of the policy.
Also the ODRL profile well be coming from this namespace.

```
"cx-policy": "https://w3id.org/catenax/policy/"
```

Also it is easier for the consumers, when using the given context, they terms are easier to read instead of expanded IRIs.

Can this please be added to the default context to also appear in the catalog?

Thanks,
Matthias

**Comment by jimmarino** [comment]
To look at adding this, we would need a valid Json-Ld context resolvable from that URL.

**Comment by arnoweiss** [comment]
I don't really see why. As I understand, the proposal is to add a prefix declaration, not the inclusion of a remote context - more like `"edc": "https://w3id.org/edc/v0.0.1"` instead of `"http://www.w3.org/ns/odrl.jsonld"`

**Comment by jimmarino** [comment]
What terms are defined in the context? We need at least a valid Json-Ld context somewhere.

**Comment by arnoweiss** [comment]
@matgnt - I understand this feature request as merely aimed at contraction of IRIs `"https://w3id.org/catenax/policy/Membership"` to `cx-policy:Membership`. There's no remote vocabulary to be pulled in, right?

**Comment by matgnt** [comment]
Yes, correct @arnoweiss : NO remote context is required for this.

**Comment by jimmarino** [comment]
OK, if there are no terms to add, then it is fine to add the prefix definition as is.

**Comment by wolf4ood** [comment]
Closed by https://github.com/eclipse-tractusx/tractusx-edc/pull/1201
