### ISSUE TITLE
[BusinessPartnerGroupExtension] Operator "in" is not a valid odrl constraint operator. 

### ISSUE THREAD

**Issue by domreuter** [eclipse-tractusx/tractusx-edc#1103]
## Describe the bug

The "in" operator used within the businessPartnerGroup Extension is not a valid odrl constraint operator.

### Expected Behavior

Use the "odrl:isPartOf" operator for scalar and non-scalar values to indicate that a given value is contained by the right operand of the Constraint.

Update the documentation here: 

https://github.com/eclipse-tractusx/tractusx-edc/tree/0.6.0/edc-extensions/bpn-validation#business-partner-group-policy

to use the updated operators to stick as close as possible to the standard within the payloads. See changes in section below.

## Context Information

For additional information:
https://www.w3.org/TR/odrl-vocab/#term-Operator
https://www.w3.org/TR/odrl-vocab/#term-isPartOf

## Possible Implementation

Refactor org.eclipse.edc.policy.model.Operator to reflect the correct odrl:Operators in the policy payload, as the "in" operator is inernally mapped to odrl:isPartOf.

Operator.EQ --> odrl:eq
Operator.NEQ --> odrl:neq
**Operator.IN --> odrl:isPartOf**
Operator.IS_ALL_OF --> odrl:isAllOf
Operator.IS_ANY_OF --> odrl:isAnyOf
Operator.IS_NONE_OF --> odrl:isNoneOf

**Comment by paullatzelsperger** [comment]
First, regarding the documentation of the BPN Group Function, that is correct, it should actually say 
> "..., the following ODRL operators are supported: eq, neq, ~~in~~ isPartOf, isAllOf,...", since the ODRL representation is `"isPartOf"`, not `"in"`. Feel free to provide a PR.

Second, the `Operator` enum correctly maps `IN` to the ODRL term `isAnyOf`, so how this is named internally has little bearing on the serialized JSON(-LD) representation. I therefor don't see a reason why we should change that. On the contrary, simply renaming it would cause a ton of churn and possibly breaking builds downstream, without providing any real value.

Introducing some sort of backwards compatibility would mean significant impact on the (upstream) code base and testing effort everywhere, again without providing a lot of value. 

In any event, this is not a bug, as it does not cause any incorrect behaviour or runtime error, and it should be move to [upstream EDC](https://github.com/eclipse-edc/Connector).

**Comment by domreuter** [comment]
New Issue and PR raised for docs #1117
