### ISSUE TITLE
feat: participant ID from/to IRI mapper

### ISSUE THREAD

**Issue by wolf4ood** [eclipse-tractusx/tractusx-edc#1107]
## WHAT

Implements a tractusx specific participantID from/to IRI mapper

https://github.com/eclipse-edc/Connector/issues/3930

## WHY

dsp compliance

**Comment by FORice606** [comment]
Is 1107 for "ID from/to IRI mapper" closed by below pull request? 
===> https://github.com/eclipse-edc/Connector/pull/3932

**Comment by ndr-brt** [comment]
> Is 1107 for "ID from/to IRI mapper" closed by below pull request? ===> [eclipse-edc/Connector#3932](https://github.com/eclipse-edc/Connector/pull/3932)

I think the issue here is to implement the mapper for T-X, as the ID used in catena are not `IRI` (they are simple BPN) and that goes against the ODRL ontology (`assigner` and `assignee` are subtypes of [`Party`](https://www.w3.org/TR/odrl-model/#party))
