### ISSUE TITLE
Accommodate upstream changes in TypeTransformerRegistry

### ISSUE THREAD

**Issue by saschaisele-zf** [eclipse-tractusx/tractusx-edc#1114]
## Describe the bug

After Upstream changes in [3965](https://github.com/eclipse-edc/Connector/pull/3965) and the subsequent removal of `ManagementApiTypeTransformerRegistry`, the `EdrExtension` and other Extensions are no longer functioning.

## Possible Implementation

All usages of the `ManagementApiTypeTransformerRegistry` need to be reworked and made compatible with the new context handling.

**Comment by wolf4ood** [comment]
Fixed by https://github.com/eclipse-tractusx/tractusx-edc/pull/1115
