### ISSUE TITLE
Repo doesn't follow git-flow workflow

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-tractusx/tractusx-edc#112]
## Describe the bug
In this repository the default branch is configured to be the `main` branch and currently all PRs are merged against it and also some commits were pushed directly on `main`. If I'm correct, the Catena-X Product-EDC repository uses the git-flow, which means that only the releases were merged to the `main` branch and the development happened on the `develop` branch. That means also, that the `develop` branch contains features and commits which weren't merged to `main` until now (e.g. on the `develop` branch all the maven group id's were already change regarding the migration from Catena-X Product-EDC to tractusx-edc).

As there are now already additional commits on the `main` branch which are not on the `develop`, the two branches are drifted away from each other, which makes it difficult to continue the migration from Catena-X Product-EDC  to tractusx-edc.

### Expected behavior/Possible solution
For an easier migration I would expect that the same git workflow would been used from the beginning of the migration until the end of the migration. But as it isn't the case, we need to align how we want to continue and how to clean up the repository again and if we still want to go with the git flow or not.

If we want to go with the git flow, I would recommend to do the following to clean up the repository again:
- Merge `main` into `develop` and fix all the merge conflics
- Make `develop` the default branch

If we don't want to go with the git flow:
- Merge `develop` into `main` and fix all the merge conflics
- Use `main` as the starting point for what ever git workflow we want to follow

**Comment by stephanbcbauer** [comment]
I would go for option 1 :) => gitflow. Not sure about the merge? Maybe rebase?

**Comment by Siegfriedk** [comment]
@florianrusch-zf as a side note: We currently enforce main as default branch in catenax-ng to make sure security scans are done on the right branche

**Comment by SebastianBezold** [comment]
> @florianrusch-zf as a side note: We currently enforce main as default branch in catenax-ng to make sure security scans are done on the right branche

@Siegfriedk is right. Here is the Link to our Release Guideline documenting this: https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-1

I could still add the commits from main to develop. Do you have any agreements/preferences about merge vs. rebase @florianrusch-zf ?

**Comment by florianrusch-zf** [comment]
I would like to postpone this topic until we (product-edc team) have some commiter in the project. I think this will make the alignment and transition smother!

**Comment by florianrusch-zf** [comment]
@paullatzelsperger created an DR which describes, how we wanna solve this issue #177. The plan is to still follow the git flow, but with different branches:

- `main` -> `releases`
- `develop` -> `main`

For details please have a look at the PR #177

**Comment by florianrusch-zf** [comment]
Renaming/Rebranching is done
