### ISSUE TITLE
Contract Agreement IDs are not being size validated

### ISSUE THREAD

**Issue by afonsocorreiactw** [eclipse-tractusx/tractusx-edc#1127]
## Describe the bug

The Database column related to the Contract Agreement ID has type character varying(255). Since the Contract Agreement ID is computed like:

"base64 contract definition id" : "base64 asset id" : "base64 random salt"

A large enough Contract Agreement ID, composed of a large contract definition id and a large asset id, will break the transfer process.

### To Reproduce

1. Register an Asset with a large ID (~100 chars)
2. Register a Contract Definition for that Asset also with a large ID (~100 chars)
3. Fetch the catalog for that EDC
4. Verify if the Offer ID has more than 255 chars (Offer ID and Contract Agreement ID are computed in the same manner, and have the same number of chars)
5. Negotiate the offer
6. Transfer the Offer

### Expected behavior

Either allow bigger Contract Agreement IDs to be registered, or restrict the size of the Contract Definitions ID and Asset IDs

### Screenshots/Error Messages

Snippet of the stack trace:

org.eclipse.edc.spi.persistence.EdcPersistenceException: ERROR: value too long for type character varying(255)
  at org.eclipse.edc.sql.SqlQueryExecutor.execute(SqlQueryExecutor.java:66)
  at org.eclipse.edc.connector.store.sql.transferprocess.store.SqlTransferProcessStore.insertDataRequest(SqlTransferProcessStore.java:324)
  at org.eclipse.edc.connector.store.sql.transferprocess.store.SqlTransferProcessStore.insert(SqlTransferProcessStore.java:318)

## Context Information

- - Used version TractuX EDC v0.5.3

## Possible Implementation

If the solution is to increase the allocated space to the contract agreement ID, change VARCHAR(255) to VARCHAR in the following block:

https://github.com/eclipse-tractusx/tractusx-edc/blob/main/edc-extensions/postgresql-migration/src/main/resources/org/eclipse/tractusx/edc/postgresql/migration/transferprocess/V0_0_1__Init_TransferProcess_Database_Schema.sql#L63

**Comment by paullatzelsperger** [comment]
Our recommendation is to use UUIDs as object IDs wherever possible. However, removing the size limit of 255 is probably reasonable.
