### ISSUE TITLE
Dataplane API is missing?

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-tractusx/tractusx-edc#1129]
## Describe the bug

I discovered, that in the [`lib.version.toml`](https://github.com/eclipse-tractusx/tractusx-edc/blob/bd6f22d4b68794f1b3c3bdc2c6dad40863ab1d7f/gradle/libs.versions.toml#L76) we have listed the `org.eclipse.edc:dataplane-api` extension. But for me it looks like it isn't been used somewhere.

Having this in the list, without using it, leads to the problem, that the api will be part of the swagger/open api documentation but the endpoints are not available.

### To Reproduce

_Steps to reproduce the behavior:_

- Try to find where this extension is be added to the controlplane as a dependency => I couldn't find it
- Try to do a request against any of the ["Dataplane Selector" endpoints](https://app.swaggerhub.com/apis/eclipse-tractusx-bot/tractusx-edc/0.6.0#/Dataplane%20Selector)

### Expected behavior

Everything that is documented in the swagger/open api doc should be fully functional.

### Screenshots/Error Messages

Request to reach a endpoint:

```shell
curl --location 'https://controlplane.domain/management/v2/dataplanes' \
--header 'X-Api-Key: ....'
```

Response:

```html
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 404 Not Found</title>
</head>
<body><h2>HTTP ERROR 404 Not Found</h2>
<table>
<tr><th>URI:</th><td>/management/v2/dataplanes</td></tr>
<tr><th>STATUS:</th><td>404</td></tr>
<tr><th>MESSAGE:</th><td>Not Found</td></tr>
<tr><th>SERVLET:</th><td>EDC-management</td></tr>
</table>

</body>
</html>
```

## Context Information

_Add any other context or information about the problem here._

- Tested with version: 0.5.4 and 0.6.0

## Possible Implementation

Either:
- Remove the extension at all
- Add it as a dependency to the controlplane

**Comment by ndr-brt** [comment]
I think that's a refuse, I don't know if a module called `dataplane-api` ever existed (the correct spelling was `data-plane-api`). I said was because that api module was split in 2:
- `data-plane-control-api`
- `data-plane-public-api`

 
> ```shell
> curl --location 'https://controlplane.domain/management/v2/dataplanes' \
> --header 'X-Api-Key: ....'
> ```

this api is part of the `data-plane-selector-api` module
