### ISSUE TITLE
EDR-State-Machine Thread Crashes, if a Secret in a Vault has already been Deleted

### ISSUE THREAD

**Issue by efiege** [eclipse-tractusx/tractusx-edc#1137]
## Describe the bug

The EDR-State-Machine thread seems to crash, if a secret in a vault has already been deleted. This seems to be caused by https://github.com/eclipse-tractusx/tractusx-edc/blob/b798d2c6e2be40849b5800d1ee200dc31e1a78d5/edc-extensions/edr/edr-cache-sql/src/main/java/org/eclipse/tractusx/edc/edr/store/sql/SqlEndpointDataReferenceCache.java#L191
This line throws an EDC-Exception, which is not handled anywhere. Also the corresponding EDR-Entry is not deleted, as the transaction does not succeed. As a result even after restarting the EDC the EDR-State-Machine thread proceeds to crash.

### To Reproduce

1. Successfully start a EDR-Negotiation
2. Delete the corresponding EDR-Entry in the Vault
3. EDR-State-Machine thread crashes
4. See no progress on all EDRs anymore

### Expected behavior

- EDR deleted, even if the corresponding secret is already deleted
- EDR-State-Machine proceeding to progress on transitioning EDR-states

## Context Information

- Used version: 0.5.4

Expected exception thrown in L191:

https://github.com/eclipse-tractusx/tractusx-edc/blob/b798d2c6e2be40849b5800d1ee200dc31e1a78d5/edc-extensions/edr/edr-cache-sql/src/main/java/org/eclipse/tractusx/edc/edr/store/sql/SqlEndpointDataReferenceCache.java#L182-L200

## Possible Implementation

_You already know the root cause of the erroneous state and how to fix it? Feel free to share your thoughts._

**Comment by wolf4ood** [comment]
Hi @efiege 

thanks for raising this,

is step 2) Delete the corresponding EDR-Entry in the Vault 

 happens manually as vault operation?

**Comment by wolf4ood** [comment]
Anyway we could fix the code that you pointed, but i'm not sure it's worth it. 

The all EDR state machine will be gone soon as mechanism to "refresh" token and it will be greatly simplified and handled by the refresh specification for tractusx on top of EDC data plane signaling.

Check here if you are not aware of this

- https://github.com/eclipse-tractusx/tractusx-profiles/blob/main/tx/refresh/refresh.token.grant.profile.md
- https://github.com/eclipse-tractusx/tractusx-edc/blob/main/docs/development/dataplane-signaling/tx-signaling.extensions.md

**Comment by ndr-brt** [comment]
I guess this issue won't be fixed as that code doesn't exist anymore, added the `stale` label so the stalebot can do its job
