### ISSUE TITLE
EDR-Negotiation Stuck in Refreshing State

### ISSUE THREAD

**Issue by efiege** [eclipse-tractusx/tractusx-edc#1139]
## Describe the bug

After receiving a `TransferTerminationMessage` from the providing counter-party connector the EDR gets stuck in `REFRESHING ` state. Also there has no `TransferStartMessage` message been sent by the providing counter-party connector.

### Expected behavior

- Current expected behaviour: EDR transitioning to `ERROR` state.
- Maybe also: Retry transfer

## Context Information

- Used version: 0.5.4

**Comment by wolf4ood** [comment]
Hi @efiege 

thanks for raising this, The fix i remember it was backported in 0.5.4 in this PR
https://github.com/eclipse-tractusx/tractusx-edc/pull/1013

Probably the failure reason is missing? not sure we'd have to reproduce this locally.

Anyway as outlined in the other issue #1137 , the auto refresh mechanism of spawning new transfer processes for "renewing" the EDR will be removed in the next release

**Comment by efiege** [comment]
Hi @wolf4ood,

you are right: There has been a fix backported for https://github.com/eclipse-tractusx/tractusx-edc/issues/837

However using the 0.5,4 extensions we still get `REFRESHING` EDRs. The auto refresh mechanism has been working for a few days and then again got stuck.

This may be caused by the EDR-State-Machine not handling EDRs in `REFRESHING` state.

Thanks for also pointing out, that this mechanism will be replaced in the next release. In the meantime however we urgently need this to be fixed.

**Comment by wolf4ood** [comment]
@efiege 

can you check the reason for the transfer process for being terminated with `TransferTerminationMessage` ?

**Comment by paullatzelsperger** [comment]
with the advent of DataPlane Signaling in 24.05, I think this issue will become irrelevant, since the renewal of access tokens will change drastically. Not sure we should/can invest time in this
