### ISSUE TITLE
Fully deleting a previously transferred asset

### ISSUE THREAD

**Issue by anschl** [eclipse-tractusx/tractusx-edc#1153]
Hi everyone,

Not sure if this counts as a bug but here it goes. What I did:
1. Initiate an EDR negotiation
2. Get data with `/aas/request` and enjoy the returned dataset
3. Find out the process id with `/edrs?assetId=1`
4. Delete with `DELETE /edrs/006f2220-4916-4f6b-bf65-1663dcddf970`
5. Wait a bit
6. Delete contract definition with `DELETE /v2/contractdefinitions/2`
7. Delete policy with `DELETE /v2/policydefinitions/1`
8. And finally delete asset with `DELETE /v3/assets/1`
The last step returns `Asset 1 cannot be deleted as it is referenced by at least one contract agreement`.  So I comply and want to delete the contract agreement. However, according to its swagger there is no way to delete it though. I tried doing `DELETE /v2/contractagreements` but it returned a 404.

So - how do I delete an asset and all its dependent entries?

**Comment by wolf4ood** [comment]
Hi @anschl 

I'm closing this, we spoke about it in the weekly

Thanks

**Comment by anschl** [comment]
Here's a summary of our discussion for people stumbling upon this.
It is a conceptual problem. The steps above create a contract between two participants, which is why you are not allowed to delete the contract of one participant. There's currently no way to revoke contract agreements on both participants.

If you want to delete the asset in order to reset your environment for testing, you have these options:
- Write a db query to delete the entries directly (and possibly write a Kubernetes job doing it)
- Use the in-memory deployment and restart it after testing
