### ISSUE TITLE
Add ci job for markdown linting

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-tractusx/tractusx-edc#117]
**Is your feature request related to a problem? Please describe.**
Yes, we need to provide some documentation for the repo (https://github.com/eclipse-tractusx/eclipse-tractusx.github.io). In this repo they are already using a CI job which lints all their markdown files and it was a huge task to fix all our markdown files manually.

**Describe the solution you'd like**
To always have proper formatted markdown files, it would be great to have a CI job which checks all added or modified markdown files of a PR.

**Additional context**
The repo https://github.com/eclipse-tractusx/eclipse-tractusx.github.io uses at the moment the npm package [`markdownlint-cli2`](https://www.npmjs.com/package/markdownlint-cli2) for linting the markdown files. The author of the npm package provides also a GitHub Action which could be used: https://github.com/marketplace/actions/markdownlint-cli2-action

**Comment by paullatzelsperger** [comment]
ideally we can incorporate the linting into the gradle build, so that it runs as part of eg. the `check` task
