### ISSUE TITLE
Cleanup obsolete branches

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-tractusx/tractusx-edc#118]
Currently, there are still two branches that are probably remnants of PRs that have already been merged:

- https://github.com/eclipse-tractusx/tractusx-edc/tree/chore/bump_chart_version which belongs to #97 
- https://github.com/eclipse-tractusx/tractusx-edc/tree/chore/release_helm_chart_workflow which belongs to #96

@carslen, since you were the author of the two PRs, I took the liberty to assign this issue to you 😉

**Comment by carslen** [comment]
done

**Comment by florianrusch-zf** [comment]
@carslen thank you! :-)
