### ISSUE TITLE
Create basic rules and guidelines

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-tractusx/tractusx-edc#120]
**Is your feature request related to a problem? Please describe.**
This issue deals with creating OSS ground rules that all committers and contributors must adhere to. It does not involve any code, but it will provide guidelines for how code is contributed.

**Describe the solution you'd like**
A couple of files, initially:
- `CONTRIBUTING.md`: will establish general contribution guide lines, e.g. opening discussions first
- `PR_ETIQUETTE.md`: will establish rules specifically about pull requests, both for authors and reviewers
- `code_style.md`: defines how code will look like. this will be encorced using checkstyle, but initially all checkstyle errors will be treated as warnings.

**Describe alternatives you've considered**
none. this is the bare minimum for OSS.

**Additional context**
We should strive to adopt as many of EDC's rules and guides, with small adaptations, because that will ensure a high degree of compatibility when upstreaming features, and it will leverage an already battle-proven system.

**Comment by paullatzelsperger** [comment]
i cannot yet assign this issue, but i'll work on it

**Comment by florianrusch-zf** [comment]
If we do that (especially the discussion thing), we also need to activate the Discussions for this repository 😅

**Comment by SebastianBezold** [comment]
Hi @paullatzelsperger,

repository settings have to be requested via [EF Help Desk ticket](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues).
It would be nice, if you could prefix the ticket with 'tractus-x:' this makes it easier to find all tickets related to our project, in case someone needs a template.

I think the ideas you have in regards to PR_ETIQUETTE and code style might also be interesting to share with all (i.e. via mailing list). We are already collecting some of them as project guidelines/agreements [here](https://eclipse-tractusx.github.io/docs/category/open-source-development)

**Comment by paullatzelsperger** [comment]
@SebastianBezold EF help desk ticket is [here](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2834)
