### ISSUE TITLE
EDC 0.7.0 → Missing "trustedIssuers" ?

### ISSUE THREAD

**Issue by jerzy-wachowiak** [eclipse-tractusx/tractusx-edc#1254]
Is the version 0.7.0 missing 'trustedIssuers'? Does EDC 0.7.0 run without this config?
Please compare:
HEAD
https://github.com/eclipse-tractusx/tractusx-edc/blob/57affd6c24407bb5e290586cc1f30713a2534723/charts/tractusx-connector/values.yaml#L46-L49
with
EDC 0.7.0
https://github.com/eclipse-tractusx/tractusx-edc/blob/a607be38d39eb162ac5a550d739faaced5dd7b55/charts/tractusx-connector/values.yaml#L46-L47

Should this be added to make 0.7.0 run?
https://github.com/eclipse-tractusx/tractusx-edc/blob/57affd6c24407bb5e290586cc1f30713a2534723/charts/tractusx-connector-azure-vault/templates/deployment-controlplane.yaml#L283-L286

**Comment by wolf4ood** [comment]
Hi @jerzy-wachowiak 

the trusted issuer on helm chart config has been added after the 0.7.0 in this [PR](https://github.com/eclipse-tractusx/tractusx-edc/pull/1237), and it will be available in the 0.7.1 when released.

Meanwhile trusted issuer can be configured via env vars. 

Here an example:

https://github.com/eclipse-tractusx/tractusx-edc/discussions/1222#discussioncomment-9151641

Thanks
