### ISSUE TITLE
Decentralized IDentifier Server

### ISSUE THREAD

**Issue by amnaishaq** [eclipse-tractusx/tractusx-edc#1267]
Hello, I am trying to set up a server  Decentralized IDentifier and my intention is to deploy the following connector:
edc-dataplane-hashicorp-vault with dependency onto Hashicorp Vault
 Can you please tell me which one of the following DID servers can help me?
Thank you
https://github.com/decentralized-identity/universal-resolver?tab=readme-ov-file

**Comment by jimmarino** [comment]
Please read the EDC documentation and familiarize yourself with decentralized identity technologies such as DIDs and DID resolvers.

This discussion forum is for specific technical questions. We can't provide general guidance here.
