### ISSUE TITLE
transfer-proxy-token-encryption-aes-key → Length?

### ISSUE THREAD

**Issue by jerzy-wachowiak** [eclipse-tractusx/tractusx-edc#1270]
Missing information in the documentation for:

https://github.com/eclipse-tractusx/tractusx-edc/blob/5e47d348aee3c72c070d5efb0071c4dc389eeb33/charts/tractusx-connector-azure-vault/values.yaml#L541
What are the requirements for the aes key?
1. length (128, 256)?
2. mode (GCM, CBC, ECB, CTR, etc)?
3. anything else?

`openssl enc -aes-256-cbc -k secret -P -md sha1` ?

**Comment by wolf4ood** [comment]
Hi @jerzy-wachowiak 

thanks for raising this the `transferProxyTokenEncryptionAesKey` is not needed anymore for the runtime to be working.

I think this is just a leftover for the azure helm variant. Will do a PR for removal
Thanks
