### ISSUE TITLE
EDR API needs transferprocess correllation id instead of own edc's transfer-process id to obtain token

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/tractusx-edc#1273]
## Describe the bug

I'm using the manual version to initialize the transfer and want to use GET `/v2/edrs/{transfer-process-id}/dataaddress` to get the EDR, but I don't find it with the transfer-process-id returned from POST `/v2/transferprocess`:

```json
[
    {
        "message": "Object of type EndpointDataReferenceEntry with ID=76a01c77-8144-413f-a6d8-72ceeb36ee8a was not found",
        "type": "ObjectNotFound",
        "path": null,
        "invalidValue": null
    }
]
```

### To Reproduce

_Steps to reproduce the behavior:_

1. Initiate Transfer using the classic way (negotiate, initiate transfer) and take `@id` as `transfer-process-id`
2. Perform GET `/v2/edrs/{transfer-process-id}/dataadress` -> error stated above

Logs consumer side
```
DEBUG 2024-05-03T05:51:06.73469686 TransferProcess 4718971e-90bb-4eb9-bcd4-0b3cc0073bda is now in state INITIAL
DEBUG 2024-05-03T05:51:07.470822809 [TransferProcessManagerImpl] TransferProcess 4718971e-90bb-4eb9-bcd4-0b3cc0073bda is now in state PROVISIONING
DEBUG 2024-05-03T05:51:07.516345952 TransferProcess: ID 4718971e-90bb-4eb9-bcd4-0b3cc0073bda. Provisioning
DEBUG 2024-05-03T05:51:07.521213038 [TransferProcessManagerImpl] TransferProcess 4718971e-90bb-4eb9-bcd4-0b3cc0073bda is now in state PROVISIONED
DEBUG 2024-05-03T05:51:07.538460043 [TransferProcessManagerImpl] TransferProcess 4718971e-90bb-4eb9-bcd4-0b3cc0073bda is now in state STARTING
DEBUG 2024-05-03T05:51:07.666727166 TransferProcess: ID 4718971e-90bb-4eb9-bcd4-0b3cc0073bda. Initiate data flow
DEBUG 2024-05-03T05:51:07.715238267 TransferProcess: ID 4718971e-90bb-4eb9-bcd4-0b3cc0073bda. send transfer start to http://customer-control-plane:8184/api/v1/dsp
DEBUG 2024-05-03T05:51:07.815829103 TransferProcess: ID 4718971e-90bb-4eb9-bcd4-0b3cc0073bda. send transfer start to http://customer-control-plane:8184/api/v1/dsp
DEBUG 2024-05-03T05:51:07.827130197 [TransferProcessManagerImpl] TransferProcess 4718971e-90bb-4eb9-bcd4-0b3cc0073bda is now in state STARTED
DEBUG 2024-05-03T05:51:07.831540677 [PolicyMonitorManagerImpl] PolicyMonitorEntry 4718971e-90bb-4eb9-bcd4-0b3cc0073bda is now in state STARTED
DEBUG 2024-05-03T05:51:31.19686729 [Hashicorp Vault] Failed to resolve secret 'edr--4718971e-90bb-4eb9-bcd4-0b3cc0073bda': [Failed to get secret with status 404]

```

What nevertheless is working, is using the correllation id
1. Same step 1. as before
2. Perform GET `/v2/transferprocesses/transfer-process-id` and take `correllationId`as `transfer-process-id`

### Expected behavior

_A clear and concise description of what you expected to happen._

### Screenshots/Error Messages

_If applicable, add screenshots and/or error messages to help explain your problem._

## Context Information

I'm using the following [docker](https://github.com/FraunhoferISST/puris/blob/chore/edc-0.7.0-infra/local/docker-compose.yaml) with this [infrastructure](https://github.com/FraunhoferISST/puris/blob/chore/edc-0.7.0-infra/local/docker-compose-infrastructure.yaml) and the configuration of the edcs can be found [here](https://github.com/FraunhoferISST/puris/tree/chore/edc-0.7.0-infra/local/tractus-x-edc/config). Explanation of how to start is in [Install.md](https://github.com/FraunhoferISST/puris/blob/chore/edc-0.7.0-infra/INSTALL.md) (ignore miw seeding).
I use one postgres instance with separated db.

- Used version:
tractusx/edc-controlplane-postgresql-hashicorp-vault                         0.7.0         ddd87b2827a5   13 days ago     370MB
tractusx/edc-dataplane-hashicorp-vault                                       0.7.0         2fffc07d8d96   13 days ago     421MB
- OS: Linux, Ubuntu 22.04.4 LTS
- Docker Version: 26.1.0
- `java --version`: openjdk 17 2021-09-14

## Possible Implementation

_You already know the root cause of the erroneous state and how to fix it? Feel free to share your thoughts._

**Comment by wolf4ood** [comment]
Hi @tom-rm-meyer-ISST 

thanks for raising this, let me check

**Comment by wolf4ood** [comment]
Hi @tom-rm-meyer-ISST  

I did checked and works on my tests here's a gist for the flow

https://gist.github.com/wolf4ood/c6ed54b5aa3975057da959139a003a29

From the logs i see that you are trying to fetch the EDR on the provider side?

Thanks

**Comment by wolf4ood** [comment]
Also check this test in TX which basically cover this flow

https://github.com/eclipse-tractusx/tractusx-edc/blob/main/edc-tests/edc-controlplane/fixtures/src/testFixtures/java/org/eclipse/tractusx/edc/tests/transfer/HttpConsumerPullBaseTest.java#L64
