### ISSUE TITLE
Use Eclipse Temurin as Docker base image

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-tractusx/tractusx-edc#130]
All docker images that run java code should use the Eclipse Temurin base image instead of Alpine + OpenJDK.

**Is your feature request related to a problem? Please describe.**
[Eclipse Temurin](https://hub.docker.com/_/eclipse-temurin) is the recommended one, and it is also an Eclipse project.

**Describe the solution you'd like**
- swap out all base images, remove the `apk upgrade` lines
- replace the base distribution in the test pipeline:
  `distribution: 'adopt'` --> `distribution: 'temurin'`

**Describe alternatives you've considered**
.

**Additional context**
should be done after #125 is merged, because that PR will modify Dockerfiles as well.

**Comment by wolf4ood** [comment]
Closed by https://github.com/eclipse-tractusx/tractusx-edc/pull/149
