### ISSUE TITLE
Reintroduce VC checks on Access Policies

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-tractusx/tractusx-edc#1349]
## WHAT

In the past, access policies could limit the visibility of entries in the DSP-Catalog of a Provider. This was done by executing checks of provider-configured ODRL-`Constraints` (sometimes bundled in policies) against the VCs presented by a Consumer. [As the migration notes state](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/docs/migration/Version_0.5.x_0.7.x.md#35-limitations), this mechanism was removed with tractusx-edc 0.7.0. It should be brought back.

## WHY
DSP-catalogs may hold data that is relevant for interoperability in a use-case and simultaneously sensitive, For example, the Quality use-case [registers EDC-Assets ](https://eclipse-tractusx.github.io/docs-kits/next/kits/Quality-Kit/Software%20Development%20View/Specification%20Quality%20Kit/#quality-data-offers-at-edc) on a per-part-basis. Fetching the entire catalog may allow inference about a supplier's demand which may result in a competitive disadvantage.

## HOW

I'm unsure about why and where the feature was removed in the first place so it's hard to speculate about implementation.

## FURTHER NOTES

I am not aware of a `Constraint` that is not either unchecked (thus irrelevant for access policies anyway) nor checked by data from a VC (and therefore currently ineffective). That's why this ticket is based on the assumption that access control for `catalog` entries is currently not implemented at all.

_Please be sure to take a look at
our [contribution guidelines](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/CONTRIBUTING.md) and
our [PR etiquette](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/pr_etiquette.md)._

**Comment by paullatzelsperger** [comment]
it is simply not possible to define access policies that require VCs to evaluate (beyond the default ones), because the consumer has no way of knowing _which_ credentials it would have to include in the scope of its SI token.

If you read carefully, the migration document that it is "not possible", not that it "has been removed". That feature never existed. 

However, expressing Access Policies that _don't_ require the evaluation of VCs is indeed possible, no change there.

**Comment by arnoweiss** [comment]
Thanks for the reply, I wasn't aware there's "default VCs".

**Comment by paullatzelsperger** [comment]
> Thanks for the reply, I wasn't aware there's "default VCs". 

out of the box, every DSP request requires the `MembershipCredential` (`org.eclipse.tractusx.vc.type:MembershipCredential:read`), but that can be configured. Check out the [IatpDefaultScopeExtension](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/edc-extensions/iatp/tx-iatp/src/main/java/org/eclipse/tractusx/edc/iam/iatp/IatpDefaultScopeExtension.java)
