### ISSUE TITLE
Refactor Helm charts

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-tractusx/tractusx-edc#136]
## WHAT

The TractusX-EDC Helm charts need to be refactored such that the currently "dynamically composed" chart is replaced by several focused an clearly delineated charts, while still preserving a measure of extensibility and flexibility.

## WHY
We do this to combat several issues we've encountered in the past, such as difficulties isolating supposed bugs and configuration errors, as well as to sharpen the focus on _what_ is actually provided by TractusX-EDC.

## HOW
The rationale and approach are outlined in a decision record (PR #194).

## SUBTASKS

- [x] #194 
- [x] #198 (should be done first)
- [x] #195
- [x] #196
- [x] #197 #279

**Comment by a-mesin** [comment]
Hi,

just as a reminder in case you might not know it already. Some of the URLs found in the comments in the helm chart templates lead to 404 pages.

[Example](https://github.com/eclipse-tractusx/tractusx-edc/blob/develop/charts/tractusx-connector/templates/deployment-controlplane.yaml#L284)
