### ISSUE TITLE
Published swagger documentation is not complete

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-tractusx/tractusx-edc#1393]
## Describe the bug

Since TX-EDC 0.7.3 the [published swagger documentation](https://app.swaggerhub.com/apis/eclipse-tractusx-bot/tractusx-edc/0.7.3) doesn't contain the upstream APIs.

### Expected behavior

All available APIs in TX-EDC are listed in the published swagger documentation.

## Hint

[@ndr-brt mentioned on matrix](https://matrix.to/#/!mYxOilDPMLCQhMoIVc:matrix.eclipse.org/$UV6Fe9WqoHFynbSOyxWwPi0wosvAABjVVNrA46Aa7Z4?via=matrix.eclipse.org&via=matrix.org&via=dev-null.rocks): 

> That happened because upstream changed the way api are versioned and uploaded (not on swaggerhub anymore).

They are publishing it now on their GitHub Page: https://eclipse-edc.github.io/docs/#/submodule/Connector/docs/developer/

**Comment by ndr-brt** [comment]
The short term fix would be to point to the latest management api openapi spec.
Long term fix is to generate the openapi spec from the used modules in the runtime (upstream issue: https://github.com/eclipse-edc/GradlePlugins/issues/244 )
