### ISSUE TITLE
Consider all past releases in the CHANGELOG.md

### ISSUE THREAD

**Issue by florianrusch-zf** [eclipse-tractusx/tractusx-edc#141]
## Describe the bug
E.g. the Release 0.1.6 is missing in the `CHANGELOG.md`

### Expected behavior
All release are listed in the `CHANGELOG.md`

**Comment by bcronin90** [comment]
Afaik there's a discussion to remove the CHANGELOG.md. Is there a decision for that @paullatzelsperger ?

**Comment by florianrusch-zf** [comment]
We have a decision to remove the CHANGELOG. There I close this issue. https://github.com/eclipse-tractusx/tractusx-edc/pull/579
