### ISSUE TITLE
Improve CI Workflows

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-tractusx/tractusx-edc#1445]
## WHAT

Tractus-X EDC Github Actions workflows have become quite complex, and in that there are several suboptimal spots and room for improvement. Specifically:

1. workflows, that are intended for manual-only tasks should be prefixed `manual-`, e.g. `manual-docker-publish.yaml` instead of `publish-docker.yaml`
2. workflows should be reused. Currently, the `publish-new-release.yaml` duplicates steps for publishing docker, maven, openapi, etc. This should get consolidated.
3. improvement to the release flow: 
  - configurable base: currently releases are always created off of `main`, but for isolated bugfixes we will need an option to do it off of some other branch
  - duplicated branches: we currently have `releases` and `release/x.y.z`, which seems spurious. We can probably skip the `releases` branch altogether.

4. introduction of intermediate builds: the `run-all-tests.yaml` job gets a new `scheduled` trigger, that runs tests and publishes a snapshot version every Monday at 03:00. Lets see how far we get with weekly builds, we can always move to nightlies later. The naming scheme is `X.Y.Z-<YEAR><MONTH><DAY>-SNAPSHOT`

## WHY

Implements this [decision record](https://github.com/eclipse-tractusx/tractusx-edc/tree/main/docs/development/decision-records/2024-07-18-Improvements-versioning-scheme)

## HOW

- [x] #1446
- [x] #1447
- [x] #1448
- [x] #1449

## FURTHER NOTES

// anything else you want to outline

_Please be sure to take a look at
our [contribution guidelines](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/CONTRIBUTING.md) and
our [PR etiquette](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/pr_etiquette.md)._

**Comment by ndr-brt** [comment]
@paullatzelsperger @rafaelmag110 can this be closed?
