### ISSUE TITLE
StsClientConfigurationExtension doesn't resolve secret from Vault

### ISSUE THREAD

**Issue by hemantxpatel** [eclipse-tractusx/tractusx-edc#1457]
## Describe the bug

_A clear and concise description of what the bug is._
[StsClientConfigurationExtension.java](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/edc-extensions/dcp/tx-dcp-sts-dim/src/main/java/org/eclipse/tractusx/edc/iam/dcp/sts/StsClientConfigurationExtension.java) expects a clientId / clientSecretAlias but doesn't resolve the secret from Vault.

https://github.com/eclipse-tractusx/tractusx-edc/blob/b618350633a9f08163412e84f17687900d147949/edc-extensions/dcp/tx-dcp-sts-dim/src/main/java/org/eclipse/tractusx/edc/iam/dcp/sts/StsClientConfigurationExtension.java#L62-L74

 
### To Reproduce

_Steps to reproduce the behavior:_

1. Use STS Remote Client in EDC and make a query catalog request.
2. Oauth Request to STS fails with 401 due to invalid client id / secret.

### Expected behavior

_A clear and concise description of what you expected to happen._
It should resolve secrets from vault. Similar configuration exists in [eclipse-edc/Connector](https://github.com/eclipse-edc/Connector) repo which resolves the secret from Vault.

[StsRemoteClientConfigurationExtension.java#L61-L64](https://github.com/eclipse-edc/Connector/blob/f9f4d181cd92514ef1b2d9af96d14ab7ad77757f/extensions/common/iam/identity-trust/identity-trust-sts/identity-trust-sts-remote-client/src/main/java/org/eclipse/edc/iam/identitytrust/sts/remote/client/StsRemoteClientConfigurationExtension.java#L61-L64)
```
var clientSecret = vault.resolveSecret(clientSecretAlias);
Objects.requireNonNull(clientSecret, format("Client secret could not be retrieved from the vault with alias %s", clientSecretAlias));

return new StsRemoteClientConfiguration(tokenUrl, clientId, clientSecret);
```

### Screenshots/Error Messages

_If applicable, add screenshots and/or error messages to help explain your problem._

## Context Information

_Add any other context or information about the problem here._

- Used version: [e.g. Commit Hash]
- OS: [e.g. Mac OS (M1), Windows, Linux]
- Docker Version: [e.g. 20.10.12]
- `java --version`:

## Possible Implementation

_You already know the root cause of the erroneous state and how to fix it? Feel free to share your thoughts._

**Comment by wolf4ood** [comment]
Linking the upstream issue that will also solve this once implemented and incorporated.

https://github.com/eclipse-edc/Connector/issues/4412
