### ISSUE TITLE
Charts testing

### ISSUE THREAD

**Issue by wolf4ood** [eclipse-tractusx/tractusx-edc#148]
Helm supports testing out of the box for the Charts. 
It would cool to introduce such testing in our CI pipeline.

We could probably use our Observability API for checking that the chart works as expected.

The docs for the Helm testing framework it's available [here](https://helm.sh/docs/topics/chart_tests/)

**Comment by tuncaytunc-zf** [comment]
Do we really need this? In our current business-tests we are using the helm charts to deploy two connectors, it would fail if something is wrong with them. At least this how the business-tests are implemented by now, this might be changed if we want to refactor it.

**Comment by tuncaytunc-zf** [comment]
> If I got it now business runs only with the configuration `postgfres` and `hashicorp` vault. So for example we are not testing the azure variant right?
> 
> We could have a fine grained test case on each charts variant/configuration without the need to run business tests against all of them.

We only have one helm chart `tractusx-connector` and using always the same helm chart to deploy the different variants. We just provide different image name and of course same other variables depending on the variant. Testing the azure variant would mean only provide the certain image name for azure and the required variables for it.
If we split the current business-tests into different tests then probably we would need a separate test only for helm chart but as of now I don't think this is required.
