### ISSUE TITLE
[0.8.0-rc2] Docker Images with tag 0.8.0-rc2 are missing 

### ISSUE THREAD

**Issue by hemantxpatel** [eclipse-tractusx/tractusx-edc#1493]
## Describe the bug

_A clear and concise description of what the bug is._

A new release `0.8.0-rc2` has been published but docker images for control-plane / data-plane are missing from docker hub.

### To Reproduce

_Steps to reproduce the behavior:_

1. Use  helm chart 
```
  repository = "https://eclipse-tractusx.github.io/charts/dev"
  chart         = "tractusx-connector"
  version     = "0.8.0-rc2"
  devel        = true
```
2. Deploy EDC
3. Deployment fails due to docker images not found.

### Expected behavior

_A clear and concise description of what you expected to happen._

For previous release, 0.8.0-rc1, docker images are present. Docker images should be present for this version as well.

### Screenshots/Error Messages

_If applicable, add screenshots and/or error messages to help explain your problem._

## Context Information

_Add any other context or information about the problem here._

- Used version: 0.8.0-rc2
- OS: NA
- Docker Version: NA
- `java --version`: NA

## Possible Implementation

_You already know the root cause of the erroneous state and how to fix it? Feel free to share your thoughts._

**Comment by paullatzelsperger** [comment]
image was published based off of https://github.com/eclipse-tractusx/tractusx-edc/tree/release/0.8.0-rc2 in [this workflow run](https://github.com/eclipse-tractusx/tractusx-edc/actions/runs/10366995402) and is available in docker hub: https://hub.docker.com/r/tractusx/edc-controlplane-postgresql-hashicorp-vault/tags?page=&page_size=&ordering=&name=0.8.0-rc2
