### ISSUE TITLE
API Documentation inconsistent (Catalog request)

### ISSUE THREAD

**Issue by timjaschik** [eclipse-tractusx/tractusx-edc#1500]
The new version for the management api (catalog request) is inconsistent between the overview page and the sub page. The url is not the same in both pages. In the [overview](https://github.com/eclipse-tractusx/tractusx-edc/tree/main/docs/usage/management-api-walkthrough) the new v3 url is `<MANAGEMENT_URL>/v3/catalog` but in the [sub page](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/docs/usage/management-api-walkthrough/04_catalog.md) and the older versions of the api the url is stated as `POST /v3/catalog/request HTTP/1.1`. Which new url is correct?

**Comment by ndr-brt** [comment]
in the overview the "root" path is reported, while in the sub page is the actual `request` url.
I don't see the issue here (this should have been a discussion maybe?)

**Comment by timjaschik** [comment]
Ahh I see your point. In other examples (for example contract negotiations) we have multiple paths building on top of the root path. There we need this distinction.
We were confused if the segment `request` will be removed in `v3`. It's all clear now, thanks.
