### ISSUE TITLE
Memory Leak During Transfer-PULL Operation

### ISSUE THREAD

**Issue by zub4t** [eclipse-tractusx/tractusx-edc#1519]
## Describe the bug

In a `transfer-PULL` scenario, a `requestID` is associated with a `DataSource` using a HashMap, but the associated objects are never released.

The `PipelineServiceImpl` class stores an entry in a HashMap named `sources`, linking each `requestID` to its corresponding `DataSource`. However, the function responsible for removing entries from this map is never invoked. As a result, the `sources` variable grows linearly with the number of requests, leading to a memory leak.

### To Reproduce
You can confirm this error by performing a transfer-PULL operation and then inspecting the `sources` member variable in `PipelineServiceImpl`. You'll notice that previous transfer information has not been properly cleaned up.

### Screenshots/Error Messages

Below is the memory usage profile during asset transfers via `PULL` at a rate of 10 Hz.
<img width="944" alt="image" src="https://github.com/user-attachments/assets/50d40570-e5bd-4fd2-997b-67247c3d2bda">

## Context Information
- Used version: 0.7.3

**Comment by rafaelmag110** [comment]
Fixed upstream in PR: https://github.com/eclipse-edc/Connector/pull/4441
Fixed for 0.7.3 in PR: https://github.com/eclipse-tractusx/tractusx-edc/pull/1520

**Comment by ndr-brt** [comment]
fixed in 0.7.4 and also on 0.8.0-rc3
