### ISSUE TITLE
Backport DataPlaneId null as non existing DataFlow in TransferProcess logic to version 0.7.5

### ISSUE THREAD

**Issue by bmg13** [eclipse-tractusx/tractusx-edc#1535]
## WHAT

Add a fix related with the null dataplaneId value in a TransferProcess, assuming it as terminated if no DataFlow is defined.

## WHY

Avoiding throwing exceptions when a TP can be considered terminated. Similar to https://github.com/eclipse-edc/Connector/pull/4420

## FURTHER NOTES

This the same as https://github.com/eclipse-edc/Connector/issues/4418 but transposed to the Tractus-X to be available to as a bugfix to v0.7.X

**Comment by bmg13** [comment]
@paullatzelsperger can you assign this to me please? PR is already up

**Comment by ndr-brt** [comment]
closed by #1534
