### ISSUE TITLE
Docker Build for EDC Data-Plane with Hashicorp Vault fails (Release version 0.7.3.)

### ISSUE THREAD

**Issue by eschrewe** [eclipse-tractusx/tractusx-edc#1566]
## Describe the bug

When trying to build the docker image for the EDC Data-Plane with Hashicorp Vault in release version 0.7.3, a failure occurs (see below)

### To Reproduce

- clone the tractusx-edc project
- git switch release/0.7.3
- build docker image via commandline as described [here](https://github.com/eclipse-tractusx/tractusx-edc/blob/release/0.7.3/edc-dataplane/edc-dataplane-hashicorp-vault/README.md)

### Expected behavior

The image build should finish without errors

### Screenshots/Error Messages

```
Starting a Gradle Daemon (subsequent builds will be faster)

FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':edc-dataplane:edc-dataplane-hashicorp-vault:shadowJar'.
> Could not resolve all dependencies for configuration ':edc-dataplane:edc-dataplane-hashicorp-vault:runtimeClasspath'.
   > Could not find org.eclipse.edc:control-plane-spi:0.7.1-SNAPSHOT.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/eclipse/edc/control-plane-spi/0.7.1-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/org/eclipse/edc/control-plane-spi/0.7.1-SNAPSHOT/control-plane-spi-0.7.1-SNAPSHOT.pom
       - file:/home/schrewe/.m2/repository/org/eclipse/edc/control-plane-spi/0.7.1-SNAPSHOT/maven-metadata.xml
       - file:/home/schrewe/.m2/repository/org/eclipse/edc/control-plane-spi/0.7.1-SNAPSHOT/control-plane-spi-0.7.1-SNAPSHOT.pom
       - https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/edc/control-plane-spi/0.7.1-SNAPSHOT/maven-metadata.xml
       - https://oss.sonatype.org/content/repositories/snapshots/org/eclipse/edc/control-plane-spi/0.7.1-SNAPSHOT/control-plane-spi-0.7.1-SNAPSHOT.pom
     Required by:
         project :edc-dataplane:edc-dataplane-hashicorp-vault > project :edc-dataplane:edc-dataplane-base > org.eclipse.edc.azure:data-plane-azure-storage:0.7.1 > org.eclipse.edc.azure:azure-blob-core:0.7.1

* Try:
> The project declares repositories, effectively ignoring the repositories you have declared in the settings.
   You can figure out how project repositories are declared by configuring your build to fail on project repositories.
   For more information, please refer to https://docs.gradle.org/8.5/userguide/declaring_repositories.html#sub:fail_build_on_project_repositories in the Gradle documentation.
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 24s

```

## Context Information

- Used tx-version: release/0.7.3
- OS: Ubuntu 22.04.5 LTS
- Docker Version: 27.2.1, build 9e34c9b
- `java --version`: java 21.0.3 2024-04-16 LTS
Java(TM) SE Runtime Environment (build 21.0.3+7-LTS-152)
Java HotSpot(TM) 64-Bit Server VM (build 21.0.3+7-LTS-152, mixed mode, sharing)

**Comment by ndr-brt** [comment]
0.7.3 has already been patched to 0.7.4 and 0.7.5, please use the latter and everything should be ok

**Comment by eschrewe** [comment]
I just tried the bugfix/0.7.4 and bugfix 0.7.5. 

The docker image builds are indeed working under these versions. But when running these images in my test environment, there are other problems. 

My test environment has been running stable with the 0.7.3 versions of the tx-edc connector, using the images on dockerhub. 

My intention is now, to customize the 0.7.3 version with two self-created extensions (one on the control plane and the data-plane each) 

On the control plane side, that worked already quite well, i.e. I added my own control plane extension to the build.gradle, built it and used it in my test environment. 

So I would really appreciate it, if I could do the same with the 0.7.3 version of the dataplane. 

I already saw, that the build.gradle of the above mentioned data-plane has not changed from version 0.7.3. to 0.74 or 0.7.5

I would be really grateful, if you could perhaps give me some hints, how I could fix the 0.7.3 version on my own.... 

Thanks in advance! 

Best regards
Ernst

**Comment by ndr-brt** [comment]
the issue in 0.7.3 cannot be fixed easily, the issue was that it relied on EDC (upstream modules) 0.7.1 that unfortunately had an issue in the released artifact that some of them were dependent to a snapshot version (as you can see from the error you got by gradle: `0.7.1-SNAPSHOT`). The solution was to re-release EDC upstream to 0.7.2 (with some additional fixed).
You could just try to update upstream edc to 0.7.2 and see if that works.

But, really, just upgrade to the new bugfix version (0.7.5), never trust older versions that are bugged anyway.

**Comment by paullatzelsperger** [comment]
we cannot re-release a version that was already published. `0.7.4` and `0.7.5` only contain incremental fixes (no new features), so updating should be no problem. 

If you encounter bugs with `0.7.5` please report them in the proper channels.

It is the Tractus-X EDC Team's recommendation to upgrade to `0.7.5`.

If you want to somehow "customize" (= hack) an earlier version of the data plane image, that is your prerogative, but be advised that you are on your own. You will receive **no** support for this, nor will we provide any recommendations.

From my perspective, this issue is resolved, and I will thus close it.

**Comment by eschrewe** [comment]
> the issue in 0.7.3 cannot be fixed easily, the issue was that it relied on EDC (upstream modules) 0.7.1 that unfortunately had an issue in the released artifact that some of them were dependent to a snapshot version (as you can see from the error you got by gradle: `0.7.1-SNAPSHOT`). The solution was to re-release EDC upstream to 0.7.2 (with some additional fixes). You could just try to update upstream edc to 0.7.2 and see if that works.
> 
> But, really, just upgrade to the new bugfix version (0.7.5), **never** trust older versions that are bugged anyway.

I set the upstream to 0.7.2 and it seems to work as I hoped, thanks very much @ndr-brt  :)

**Comment by eschrewe** [comment]
> We cannot re-release a version that was already published. That would also go against every software practice known to man. `0.7.4` and `0.7.5` only contain incremental fixes (no new features), so updating should be no problem.
> 
> If you encounter bugs with `0.7.5` please report them in the proper channels.
> 
> It is the Tractus-X EDC Team's recommendation to upgrade to `0.7.5`.
> 
> If you want to somehow "customize" (= hack) an earlier version of the (already published) data plane image, that is your prerogative, but be advised that you are on your own. You will receive **no** support for this, nor will we provide any recommendations.
> 
> From my perspective, this issue is resolved, and I will thus close it.

I see ... thank you for taking the time to respond anyways ...

**Comment by paullatzelsperger** [comment]
> I set the upstream to 0.7.2 and it seems to work as I hoped, thanks very much @ndr-brt :)

You are intentionally creating technical debt. We explicitly advise **against** doing that.
