### ISSUE TITLE
`0.7.5` Duplicate Transfer-Data-Plane-Signaling Dependencies in `edc-controlplane-base` Module?

### ISSUE THREAD

**Issue by wolf4ood** [eclipse-tractusx/tractusx-edc#1577]
### Discussed in https://github.com/eclipse-tractusx/tractusx-edc/discussions/1576

<div type='discussions-op-text'>

<sup>Originally posted by **efiege** September 23, 2024</sup>
During our review of the dependency tree for the `edc-controlplane-postgresql-azure-vault` module, we observed that both the following dependencies are being included:

- org.eclipse.edc:transfer-data-plane-signaling:0.7.2
- project :edc-extensions:transfer-dataplane-signaling

It appears that the version included in this repository is a patched version of `org.eclipse.edc:transfer-data-plane-signaling:0.7.2`, addressing this issue: https://github.com/eclipse-tractusx/tractusx-edc/pull/1534.

However, having both dependencies included might result in the registration of two `DataPlaneSignalingFlowController` instances within the `DataFlowManager`, one with the fix and one without. This could potentially cause the EDC to load the unpatched version, depending on how it resolves these extensions.

The unpatched core EDC version is referenced here:

https://github.com/eclipse-tractusx/tractusx-edc/blob/75d1526115bf3922c204aea4ff8434a1b37eb514/gradle/libs.versions.toml#L233

https://github.com/eclipse-tractusx/tractusx-edc/blob/75d1526115bf3922c204aea4ff8434a1b37eb514/edc-controlplane/edc-controlplane-base/build.gradle.kts#L70
</div>

**Comment by wolf4ood** [comment]
@bmg13 could you check on this ?

Thanks

**Comment by bmg13** [comment]
hey @wolf4ood good point, please assign it to me, will try to address it in the meantime

**Comment by rafaelmag110** [comment]
@wolf4ood this was merged. Can it be closed?
