### ISSUE TITLE
Refactor: remove private backendservice from helmcharts

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/tractusx-edc#161]
Right now there is a private backend service used (from a private repository) within our helmchart

The service is used in the supporting infrastructure [helm chart](https://github.com/eclipse-tractusx/tractusx-edc/blob/develop/edc-tests/cucumber/src/main/resources/deployment/helm/supporting-infrastructure/Chart.yaml)

Private service/repository [here](https://github.com/eclipse-tractusx/tractusx-edc/blob/c6ea80d27926471ffdf5ac3e7fe648fef39edd30/edc-tests/cucumber/src/main/resources/deployment/helm/supporting-infrastructure/Chart.yaml#L57)

Within this ticket, it should be analyzed if we really need this service. If we require it we should think about how to redevelop it and also store it in our repository or under a separate repository under tractusx.

Tasks

- [ ] Analyze the service
- [ ] extract the service
- [ ] store it in a new repository
- [ ] link the new service in the helm chart

**Comment by paullatzelsperger** [comment]
applied the `bug` label, because private code in OSS is ... well... a bug :)

**Comment by wolf4ood** [comment]
Closed by https://github.com/eclipse-tractusx/tractusx-edc/pull/176
