### ISSUE TITLE
Extend the tractusx-github.io "control Plane adpater" documentation

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/tractusx-edc#162]
I want to get more information about the control plane adapter on [tractusx-github.io](https://eclipse-tractusx.github.io/docs/category/connector-kit)

Within this [PR](https://github.com/eclipse-tractusx/tractusx-edc/pull/137) a openAPI.yaml was generated. This should also be available in our kit documentation.

We also should be sure if the control plane adapter is documented in md. 

Tasks
 - [ ] Adapt tractusx.github.io
 - [ ] Generate mdx files out of openAPI file
 - [ ] Link them
 - [ ] Add documentation to tractusx.github.io (since we dont use submodules, this has to be done manual)

**Comment by stephanbcbauer** [comment]
@tuncaytunc-zf can we have a call on this? Is the related PR/changes? obsolete? Should we document something here?

**Comment by saschaisele-zf** [comment]
I would reckon that this issue is obsolete at this point?
A full documentation with examples and error codes can be found on [swaggerhub](https://app.swaggerhub.com/apis/eclipse-tractusx-bot/tractusx-edc/0.6.0-rc1).
