### ISSUE TITLE
EDC 0.7.x - Use of Keyword "action":"USE"/"use" in access and usage policies not consistent and not working reliably

### ISSUE THREAD

**Issue by gerbigf** [eclipse-tractusx/tractusx-edc#1649]
## Describe the bug

Disclaimer: This issue might be complex to explain and understand - feel free to ask for more context. 

The effect of the keywords "action": "USE" and "action": "use" in access and usage policies is inconsistent and their effect depends on details in the syntax. Furthermore, the documentation in the walkthrough lets you create not working access policies that expose offers to partners even if they don't fulfil the access policy

### access policies ###
1. In Access Policies: The documentation here: https://github.com/eclipse-tractusx/tractusx-edc/blob/main/docs/usage/management-api-walkthrough/02_policies.md uses a syntax ("action": "use",) that the EDC will expand to "odrl:action":"odrl:use". This notation will lead to the actual access policy being ignored and the contract definition is visible even when the access policy is not fulfilled. 
2. In Access Policies: Using a different notation: "action": "USE" will expand to "odrl:action": "edc:USE" leading to the same behaviour as in 1. 
3. The only thing that consistently works in access policies is `"action": {"@id":"USE"}` which will not expand the USE keyword. 

### usage policies###
For usage policies it's the exact opposite. Using "USE" as the keyword will lead to the required credentials not being requested during contract negotiation. 

### To Reproduce

_Steps to reproduce the behavior:_

For 1. in the access policies: 

Create the following access policy 

```json
{
    "@context":[
    "http://www.w3.org/ns/odrl.jsonld",
    {
      "@vocab": "https://w3id.org/edc/v0.0.1/ns/",
    },
  ],
	"@id": "access-policy-demo",
	"@type": "PolicyDefinition",
	"policy": {
		"@type": "Set",
		"permission": {
			"action": "use",
			"constraint": {
				"and": [
					{
						"leftOperand": "BusinessPartnerNumber",
						"operator": "eq",
						"rightOperand": "BPNLXXXX"
					}
				]
			}
		},
		"prohibition": [],
		"obligation": []
	}

}
```

For 2. the access policy looks as follows: 
```json
{
    "@context":[
    "http://www.w3.org/ns/odrl.jsonld",
     "https://w3id.org/tractusx/edc/v0.0.1",

    {
      "@vocab": "https://w3id.org/edc/v0.0.1/ns/",
    },
  ],
	"@id": "access-policy-demo",
	"@type": "PolicyDefinition",
	"policy": {
		"@type": "Set",
		"permission": {
			"action": "USE",
			"constraint": {
				"and": [
					{
						"leftOperand": "BusinessPartnerNumber",
						"operator": "eq",
						"rightOperand": "BPNLXXXX"
					}
				]
			}
		},
		"prohibition": [],
		"obligation": []
	}

}
```

The only working access policy: 
```json
{
    "@context":[
    "http://www.w3.org/ns/odrl.jsonld",
     "https://w3id.org/tractusx/edc/v0.0.1",
    {
      "@vocab": "https://w3id.org/edc/v0.0.1/ns/",
    },
  ],
	"@id": "access-policy-demo",
	"@type": "PolicyDefinition",
	"policy": {
		"@type": "Set",
		"permission": {
			"action": {"@id":"USE"},
			"constraint": {
				"and": [
					{
						"leftOperand": "BusinessPartnerNumber",
						"operator": "eq",
						"rightOperand": "BPNLXXXX"
					}
				]
			}
		},
		"prohibition": [],
		"obligation": []
	}

}
```

### Expected behavior

The use of the keywords "action":"use" should be consistent across access and usage policies and leads to consistent results when viewing the catalogue and negotiation contracts. 

### Screenshots/Error Messages

_If applicable, add screenshots and/or error messages to help explain your problem._

## Context Information

_Add any other context or information about the problem here._

- Used version: 0.7.6
- OS: Mac

## Possible Implementation

I'm happy to update the documentation once we've reached alignment on how it should look like correctly!

**Comment by wolf4ood** [comment]
Hi @gerbigf 

the `USE` should not be used as it stays there for backward compatibility and it's not odrl compliant.

the right action is `use` .

The right one is the 1. example as stated in the documentation. The one you posted i think it misses the `https://w3id.org/tractusx/edc/v0.0.1` context and thus the `BusinessPartnerNumber` will get default under the `@vocab` which is EDC one,
and the function will not be triggered.

https://github.com/eclipse-tractusx/tractusx-edc/blob/main/docs/usage/management-api-walkthrough/02_policies.md#partner-1---access-policy-example-scenario-1

**Comment by gerbigf** [comment]
I see. So my issue wasn't really with the "use" "USE" but that I used different contexts in my samples. If the capital USE is deprecated, should we add a deprecation warning?

**Comment by wolf4ood** [comment]
Yeah is the "USE" still mention in this repo, i would put a deprecation warning
