### ISSUE TITLE
Adapt documentation – Add link to product installation manual in root readme.md

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/tractusx-edc#170]
The installation manual for the tractusx-edc is not easy to find. For new user, it should be mentioned and also linked in the README.md (root)

It is also a requirement for the FOSS QGate.

**Comment by SebastianOpriel** [comment]
@stephanbcbauer Could you share the link with me? Is it on confluence oder in Teams?

**Comment by stephanbcbauer** [comment]
> @stephanbcbauer Could you share the link with me? Is it on confluence oder in Teams?

Hey @SebastianOpriel this issue is first a reminder for myself, to link the future installation manual in the readme.md, cause this is a requirement by the system team. So in the end, the manual which should be linked is the new one you will create. :)

Right now, we don't have a clear installation manual. Here are the links which maybe is a manual somehow: :)

1. Important for testing, after installation -> [postman collection](https://github.com/eclipse-tractusx/tractusx-edc/tree/main/docs/development/postman)
2. [local setup cp](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/docs/kit/operation-view/page03_local_setup_controlplane.md) -> but that's not where we want to start from. Starting from given helm chart would be better.
3. [local setup db](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/docs/kit/operation-view/page04_local_setup_dataplane.md) -> see 2. 
4. [setup in kubernetes via helm](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/docs/kit/operation-view/page06_kubernetes_setup.md) -> better but not detailed enough
5. [local setup](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/docs/samples/Local%20TXDC%20Setup.md) -> but here an [infrastructure](https://github.com/eclipse-tractusx/tractusx-edc/tree/main/edc-tests/cucumber/src/main/resources/deployment/helm/supporting-infrastructure) is needed. 

As you can see, there is not a clear manual how ti install/setup/confiure a edc. Thats why we need you

**Comment by SebastianOpriel** [comment]
Thanks for clarification 😊 we will do our best to provide a profound tutorial 👍

**Comment by florianrusch-zf** [comment]
@SebastianOpriel @stephanbcbauer could you both provide an update regarding this issue?

**Comment by SebastianOpriel** [comment]
@tmberthold @AbdullahMuk

**Comment by tmberthold** [comment]
Agree, would also need a good guide, perhaps those who have set up the Tractus-X so far can put one together.

**Comment by stephanbcbauer** [comment]
Mh i am not sure... do we have the installation guide now? does the installation manual in the helm chart readmes count?
