### ISSUE TITLE
Get rid of deprecated charts

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-tractusx/tractusx-edc#171]
Currently we have "deprecated" charts that aren't providing value and they are a pain to maintain.

**Is your feature request related to a problem? Please describe.**
Maintenance of dead code

**Describe the solution you'd like**
Delete the `edc-controlplane` and `edc-dataplane` charts, as they have been replaced by the `tractus-connector` one

**Describe alternatives you've considered**
.

**Additional context**
.

**Comment by wolf4ood** [comment]
Closed by https://github.com/eclipse-tractusx/tractusx-edc/pull/178
