### ISSUE TITLE
Adapt Postman collection for v0.3.x

### ISSUE THREAD

**Issue by tuncaytunc-zf** [eclipse-tractusx/tractusx-edc#228]
WHAT
The current Postman collection URL are pointing to `/data/` and should be use `/management/` as it is the default setup.
To make it more flexibel the URL prefix like `/management/` should be added to variable definition.

Example variable definition:
`{{PROVIDER_DATAMGMT_URL}}/data/assets` -> `{{PROVIDER_DATAMGMT_URL}}/assets` where `{{PROVIDER_DATAMGMT_URL}}` would look like `<host>:<port>/management`

Add Control Plane Adapter calls to the collection

**Comment by paullatzelsperger** [comment]
just FYI: this can be easily scaffolded by importing the `openapi.yaml` file into Postman. some manual fixes may be necessary, but the grunt work can be automated.

**Comment by tuncaytunc-zf** [comment]
> just FYI: this can be easily scaffolded by importing the `openapi.yaml` file into Postman. some manual fixes may be necessary, but the grunt work can be automated.

I know that, I have already imported the whole `openapi.yaml` locally ;-)  but this is more about adapting the whole calls to be able to run against the current configuration/setup with example content and also using just the relevant calls.
