### ISSUE TITLE
Create EDC installation guide

### ISSUE THREAD

**Issue by tmberthold** [eclipse-tractusx/tractusx-edc#275]
### Discussed in https://github.com/eclipse-tractusx/tractusx-edc/discussions/270

<div type='discussions-op-text'>

<sup>Originally posted by **tmberthold** April 21, 2023</sup>
**WHAT**
Create a documentation on how to deploy a Catena-X EDC via helm charts from scratch (e.g. to azure). This documentation should be used as installation guide for companies willing to deploy EDC. Outcome should be aligned with Catena-X standards and components. Documentation deployed in Tractus-X.

**WHY**
Various documentations at different locations exists, which makes it difficult to deploy an EDC Connector for Catena-X. 

**SOLUTION PROPOSAL**
-	Step-by-step installation guide
-	Highlight basic requirements for installation (e.g. Java, Kubernetes, maven…)
-	Document prerequisites or external sources
-	Document required configurations, properties etc.

**FURTHER NOTES**
Continuous improvement of documentation planned. Starting with first minimal viable documentation which will be enhanced over time.

--

If such a guide already exist, please let us know and link it :) Otherwise we are happy to make our contribution and start with such a guide.
Also refers to https://github.com/eclipse-tractusx/tractusx-edc/issues/170</div>

@DominikPinsel @stephanbcbauer @sebk46

**Comment by stephanbcbauer** [comment]
@bcronin90 isnt this done (or at least planned) with the new operation view in the new structure of the connector Kit?

**Comment by bcronin90** [comment]
@stephanbcbauer Imo this documentation already exists and yes, the new operation view will link to it once it is merged.
