### ISSUE TITLE
SystemTeam: QG4 checks (Release 3.1)

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/tractusx-edc#277]
## QG checks
Please keep this issue open until QG X is concluded and will be managed by the Issue Creator!
We will inform you about finding and proposals in separated issues, this issue here is for the Overview of the Checks!

### Please keep this issue open until QG4 is concluded!

Product Name: tractusx-edc
Product Owner: Stefan Ettl
Dev SPOC:
Helm Chart Version: 0.3.3
App Version: 0.3.3
QG4 Approval: yes/no

##### TRG 1.01
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-1
- [x] an appropriate `README.md` file
###### TRG 1.02
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-2
- [x] an appropriate `INSTALL.md`
###### TRG 1.03
https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-3
- [x] an appropriate `CHANGELOG.md`
    - [x] the versioning itself follows [semantic versioning](https://semver.org/)
##### TRG 2.01
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-1
- [x] default branch is named `main`
##### TRG 2.03
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3
- [x] `/docs` directory contains detailed product related documentation for the Tractus-X product
- [x] `/charts` directory contains the Helm chart for the Tractus-X product IF available
- [x] `AUTHORS.md` file (optional)
- [x] `CODE_OF_CONDUCT.md` file
- [x] `CONTRIBUTING.md` file
- [ ] `DEPENDENCIES` file(s) with up to date content (Dash tool generated)
- [x] `LICENSE` file
- [x] `NOTICE.md` file
- [x] `SECURITY.md` file
##### TRG 2.04
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-4
- [x] a Leading product repository
- [x] repository name must be _productname_ without prefix or suffix
- [x] should contain the release
- [x] references/urls to the product's other repositories
- [x] might contain product helm chart
- [x] README.md: contains the urls for the backend and frontend applications
##### TRG 2.05
https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5
- [x] #280
- [x] file has a proper format
##### TRG 3.02
https://eclipse-tractusx.github.io/docs/release/trg-3/trg-3-2
- [x] if data persistence is needed in Kubernetes the use of PersistentVolume and PersistentVolumeClaim resource
##### TRG 4.01
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-1
- [x] All images must be tagged following [semantic versioning](https://semver.org/)
- [x] container is labeled correctly additionally to the latest tag
##### TRG 4.02
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-2
- [x] must add a section to your top level `README.md` file, that contains information about the used base image
- [x] Java, Kotlin, ... if JVM based language use base image from [Eclipse Temurin](https://hub.docker.com/_/eclipse-temurin)
##### TRG 4.03
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-3
- [x] image has `USER` command to specify a non-root user to run the container
- [x] `deployment.yaml` has `runAsUser` and `allowPrivilegeEscalation: false` properly set
##### TRG 4.05
https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-5
- [x] released image must be present on `GitHub Package registry` or `Dockerhub`
##### TRG 5.01
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-01
- [x] Helm chart must be released
- [x] appropriate semantic versioning for `version` and `appVersion` has to be used in `Chart.yaml`
- [x] must not contain any environment specific `values-xyz.yaml`
- [x] `values.yaml` file must contain proper default values/placeholders
- [x] No hostname provided for ingress
- [x] Ingress is disabled
- [x] No references to any secret engine service (e.g.: Hashicorp Vault)
- [x] Dependencies should be prefixed with the nameOverride and/or fullnameOverride properties
- [x] Image tag is set to the `Chart.yaml` `appVersion` property
- [x] #283
- [x] dependencies have to be declared in Chart.yaml NOT requirements.yml
##### TRG 5.02
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-02
- [x] Helm chart location inside Git repository in `/charts` directory
- [x] chart file structure
``` markdown
charts/ 
    chartNameA/
      Chart.yaml
      ... 
    chartNameB/
      Chart.yaml
      ...
AUTHORS.md 
DEPENDENCIES.md 
LICENCE 
README.md 
```
- [x] #284
- [x] latest tag is not used in helm chart be default
##### TRG 5.04
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-04
- [x] CPU and memory limits and requests are properly set
##### TRG 5.06
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-06
- [x] every startup configuration aspect of your application must be configurable through the Helm chart (ingress class, tls, labels, annotations, database, secrets, persistence, env variables)
##### TRG 5.07
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-07
- [x] if dependencies are present in the `Chart.yaml` they are properly configured
##### TRG 5.08
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-08
- [x] a product has a single deployable helm chart that contains all components (backend, frontend, etc.)
- [x] name of the Chart should be just the product-name without prefix or suffix
- [x] values file should contain all available variables (even from subcharts) with default values and comments about what they do
- [ ] helm install command should successfully install the chart to any supported Kubernetes version cluster (without overwriting default values)
- [ ] helm test runs without errors

#### Testing
- [ ] installed and running on pre-prod without errors

**Comment by SebastianBezold** [comment]
Hi @stephanbcbauer,
you mentioned the Chart `version` 0.3.3 in your description. I can see that the `appVersion` in that Chart is also 0.3.3. I guess also the [tag 0.3.3](https://github.com/eclipse-tractusx/tractusx-edc/releases/tag/0.3.3) is the one, that the release was built from, right?

**Comment by SebastianBezold** [comment]
Hi @stephanbcbauer, could you please help me out on the 'link to other repositories' part. AFAIK, the tractusx-edc is the only repository maintained by your team in eclipse-tractusx right? Like the connector components, but if I'm not mistaken, they are not part of the eclipse-tractusx org right?
If there would be related repos/products (not talking about products depending on the tractusx-edc), then we have a guideline on how you should 'link' them via metadata file: https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5

**Comment by SebastianBezold** [comment]
> Hi @stephanbcbauer, could you please help me out on the 'link to other repositories' part. AFAIK, the tractusx-edc is the only repository maintained by your team in eclipse-tractusx right? Like the connector components, but if I'm not mistaken, they are not part of the eclipse-tractusx org right? If there would be related repos/products (not talking about products depending on the tractusx-edc), then we have a guideline on how you should 'link' them via metadata file: https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-5

I created #280 , since the file itself is not present. It should anyways be present, even if there are no supporting repositories other that this one here. This metadata file will be used in upcoming automation

**Comment by SebastianBezold** [comment]
General remark @stephanbcbauer:
I am not sure about the state of your `DEPENDENCIES`. Can you please check, if it is out of date? There are `restricted` dependencies listed, that might be approved in the meantime. Can you do another dash run to update the restricted dependencies and see, if there are new IP checks necessary? I could also create an issue for that if you want to track it separately

**Comment by stephanbcbauer** [comment]
> General remark @stephanbcbauer: I am not sure about the state of your `DEPENDENCIES`. Can you please check, if it is out of date? There are `restricted` dependencies listed, that might be approved in the meantime. Can you do another dash run to update the restricted dependencies and see, if there are new IP checks necessary? I could also create an issue for that if you want to track it separately

@SebastianBezold not sure if you have a template for this issue. But it would be really cool to create an issue for that. thx

**Comment by stephanbcbauer** [comment]
> Hi @stephanbcbauer, you mentioned the Chart `version` 0.3.3 in your description. I can see that the `appVersion` in that Chart is also 0.3.3. I guess also the [tag 0.3.3](https://github.com/eclipse-tractusx/tractusx-edc/releases/tag/0.3.3) is the one, that the release was built from, right?

@SebastianBezold yes that's correct

**Comment by stephanbcbauer** [comment]
@SebastianBezold which branch is here under test? Is it main? Or release? @tuncaytunc-zf  fyi

**Comment by stephanbcbauer** [comment]
@tuncaytunc-zf just a summary (by @SebastianBezold  because I don't know right now which should be fixed with the new release 0.3.4:

1. Almost all checks passed.
2. released Chart for version 0.3.3 does not start up -> should be fixed in a new bugfix release (Chart version bump would be enough appVersion can stay untouched)
3. Unclear how to proceed with "out of date" legal docs. DEPENDENCIES out of date and in the release do contain restricted libs, wich would be ok for development, but not for release
4. Some license and copyright headers are missing in the released tag, since ~80% are present, we could argue, that we did our due diligence and just missed out on some. Should be fixed on latest main though

--------
2. is this fixed with the new release?
3. die we already follow the process here? generating IP tickets aso? does this solve the issue?
4. this should be an easy fix?

thx

**Comment by SebastianBezold** [comment]
> @tuncaytunc-zf just a summary (by @SebastianBezold ) because I don't know right now which should be fixed with the new release 0.3.4:
> 
> 1. Almost all checks passed.
> 2. released Chart for version 0.3.3 does not start up -> should be fixed in a new bugfix release (Chart version bump would be enough appVersion can stay untouched)
> 3. Unclear how to proceed with "out of date" legal docs. DEPENDENCIES out of date and in the release do contain restricted libs, wich would be ok for development, but not for release
> 4. Some license and copyright headers are missing in the released tag, since ~80% are present, we could argue, that we did our due diligence and just missed out on some. Should be fixed on latest main though
> 
> 2. is this fixed with the new release?
> 3. die we already follow the process here? generating IP tickets aso? does this solve the issue?
> 4. this should be an easy fix?
> 
> thx

Hi @stephanbcbauer and @tuncaytunc-zf, 
details on 
2. -> The logic to select the image to use based on config does not resolve to a valid image. This results in ` cannot choose control-plane image automatically based on configuration` errors, if there is no further config. We aim for working defaults, so anyone could at least try out the Chart in a basic config without much effort.
3. -> If you are creating a 0.3.4 release, this should be easy to include. From a release point of view. Every used 3rd party dependency must be listed in the DEPENDENCIES and every lib has to be approved by the EF.

**Comment by stephanbcbauer** [comment]
@SebastianBezold, @Siegfriedk could you please check again the following requirements

1. TRG 2.03 DEPENDENCIES file(s) with up-to-date content (Dash tool generated) -> was generated again, missing IP requests were created -> no rejected LIBS anymore
2. TRG 2.05 file has a proper format -> file was created -> format should be fine
3. TRG 5.08 helm install command should successfully install the chart to any supported Kubernetes version cluster (without overwriting default values) -> not possible on our side (because we are using daps) and therefore certificates are needed. But we adapted the documentation #352 how to use/generate the needed parameters.
4. TRG 5.08 helm test runs without errors -> related to 3.
5. installed and running on pre-prod without errors -> can you try this again?

add on "_> The logic to select the image to use based on config does not resolve to a valid image. This results in  cannot choose control-plane image automatically based on configuration errors, if there is no further config. We aim for working defaults, so anyone could at least try out the Chart in a basic config without much effort._" -> now there is a default image used if no image is selected

@paullatzelsperger , @stefan-ettl FYI -> If these requirements are fulfilled now, we can create the new release 0.3.4

**Comment by Siegfriedk** [comment]
@stephanbcbauer if you use daps, you should pull daps in as a default dependency

**Comment by Siegfriedk** [comment]
@stephanbcbauer no clue and i don't mind closing it. We discussed all critical things together, i assume you are aware of our trgs and we will do a new review with 3.2.
