### ISSUE TITLE
delete keys from repository

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/tractusx-edc#278]
## Describe the bug

GitGuardien mentioned some issues with our dummy keys in our repository. They are only used for testing purpose and are not valid in the outside world, but there is a need to get rid of them

### Expected behavior

The keys should be stored in the repository.

### Screenshots/Error Messages

![image](https://user-images.githubusercontent.com/84396022/234194719-9f497766-28ae-4f03-ab7f-96dd11b246ed.png)

## Possible Implementation (already discussed in teams)

- if we just delete them, some of our GH test actions would fail
- i see two ways forward: a) convince whoever mandated their deletion, that test keys are not really harmful, or b) go Florian Rusch (Guest)'s route an regenerate them every test run. 

b) is cleaner, but more effort

**Comment by paullatzelsperger** [comment]
i don't think this is a bug. nothing is broken, and no functionality is hampered in any way. @stephanbcbauer would you mind moving this to the feature board and removing the `bug` label?

**Comment by bcronin90** [comment]
In the past we generated test keys on the fly, so they only ever existed at runtime. Would this be a viable solution here? We basically already have the functionality and could generalize that.

**Comment by paullatzelsperger** [comment]
@bcronin90 yes, that is the task, and it will need to be done for the business tests and the deployment tests.

**Comment by bcronin90** [comment]
Thanks for the confirmation. Feel free to assign it to me then.

**Comment by bcronin90** [comment]
> @bcronin90 yes, that would work fine. It will need to be done for the business tests and the deployment tests. We would need to include this into the "how-to-run-stuff-locally" documentation, as users would have to generate certs/PKs as well.

That should all be rather easy to do with bouncycastle. Are we allowed to use that? If so, please feel free to assign the issue to me.

**Comment by paullatzelsperger** [comment]
> > @bcronin90 yes, that would work fine. It will need to be done for the business tests and the deployment tests. We would need to include this into the "how-to-run-stuff-locally" documentation, as users would have to generate certs/PKs as well.
> 
> That should all be rather easy to do with bouncycastle. Are we allowed to use that? If so, please feel free to assign the issue to me.

I assigned it to you. Regarding BC: what do you have in mind? I was thinking of mostly the command line, as it provides all necessary tools, does not require additional code and is very portable - the `openssl` program in particular.

**Comment by stephanbcbauer** [comment]
@bcronin90 , @paullatzelsperger there is currently no assignee. is somebody working on it?
