### ISSUE TITLE
Chart does not provide fallback image that is used, if no further config done

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/tractusx-edc#283]
## Description 

I tried to deploy the `tractusx-connector` chart in version `0.3.3` without doing any further configuration, than what is provided as default. This did not work, since the helm templating failed with the following error (condensed): 

```
rpc error: code = Unknown desc = Manifest generation error (cached): `helm template 
... 
 cannot choose control-plane image automatically based on configuration Use --debug flag to render out invalid YAML
```

## Expected behavior

The connector should provide defaults, that will at least render successfully and start the application, even though it might miss configuration to properly function

## Additional hints

The image selection logic already seems sophisticated enough. See [deployment](https://github.com/eclipse-tractusx/tractusx-edc/blob/0.3.3/charts/tractusx-connector/templates/deployment-controlplane.yaml#L62-L74).
I guess, tweaking the default `values.yaml` to have a simple fallback (i.e. in-memory persistance, bring your own vault) should do the trick

**Comment by tuncaytunc-zf** [comment]
@SebastianBezold this is already fixed in the current (main) branch and would go into the next release:
```
          # either use the specified image, or use the default one
          {{- if .Values.controlplane.image.repository }}
          image: "{{ .Values.controlplane.image.repository }}:{{ .Values.controlplane.image.tag | default .Chart.AppVersion }}"
          {{- else }}
          image: "tractusx/edc-controlplane-postgresql-hashicorp-vault:{{ .Values.controlplane.image.tag | default .Chart.AppVersion }}"
          {{- end }}
```

**Comment by tmberthold** [comment]
Is it already foreseeable when the next release will happen? This could be important for the installation guide, otherwise we will have to describe a different approach then those 2 readme lines plus config to get it currently running :)
