### ISSUE TITLE
Older TransferProcess objects cause NullPointerException

### ISSUE THREAD

**Issue by yurimssilva** [eclipse-tractusx/tractusx-edc#296]
## Describe the bug

- The latest `TransferProcess` migration adds the `transferprocess_properties` column as nullable and does not set a default value for it, making all the existing tuples have this column as `NULL`.
The `TransferProcess.getProperties` method does not verify this attribute's nullability when it tries to turn it into an unmodifiable map causing a NullPointerException to be thrown.

### To Reproduce

1. Through DMA fetch a `TransferProcess` object having the `transferprocess_properties` column as NULL (e.g. 0.1.6 objects).

### Expected behavior

- The older objects returned with the property as an empty map.

## Context Information

- Used version: 0.3.0

## Possible Implementation

- New migration defining the new coloumn's default value to `{}` and/or verifying nullability in code.

**Comment by bcronin90** [comment]
I don't have the permissions to assign this to myself, but I'll have a look at it.
