### ISSUE TITLE
Fix misspelled `gradlew` commands in the documents

### ISSUE THREAD

**Issue by sekikn** [eclipse-tractusx/tractusx-edc#302]
## Describe the bug

There are some misspelled `gradlew` commands in the documents. It would be better to fix them so that users can copy-and-paste the command as it is.

```
$ git grep gardlew
docs/kit/operation-view/page03_local_setup_controlplane.md:./gardlew :edc-controlplane:edc-controlplane-postgresql-hashicorp-vault:dockerize
docs/kit/operation-view/page04_local_setup_dataplane.md:./gardlew :edc-dataplane:edc-dataplane-hashicorp-vault:dockerize
edc-controlplane/edc-controlplane-postgresql-hashicorp-vault/README.md:./gardlew :edc-controlplane:edc-controlplane-postgresql-hashicorp-vault:dockerize
edc-controlplane/edc-controlplane-postgresql/README.md:./gardlew :edc-controlplane:edc-controlplane-postgresql:dockerize
edc-dataplane/edc-dataplane-azure-vault/README.md:./gardlew :edc-dataplane:edc-dataplane-azure-vault:dockerize
edc-dataplane/edc-dataplane-base/README.md:./gardlew :edc-dataplane:edc-dataplane-base:build
edc-dataplane/edc-dataplane-hashicorp-vault/README.md:./gardlew :edc-dataplane:edc-dataplane-hashicorp-vault:dockerize
```

**Comment by sekikn** [comment]
Hi Tractus-X team,

Recently I'm interested in Tractus-X and trying to run it locally. During that trial, I found some minor issues mainly in its documentation. I'd be glad if I could contribute PRs for them.

**Comment by florianrusch-zf** [comment]
Hey, we are happy about every contribution 😉 Please allow me to make a quick reference to our https://github.com/eclipse-tractusx/tractusx-edc/blob/main/pr_etiquette.md regarding providing PRs.

Regarding this issue: thanks a lot for your discoveries! If you want, you can create a PR for it. This would be a "good first issue".

**Comment by sekikn** [comment]
Thanks for the reply! I'll confirm the PR etiquette and submit a PR soon.
