### ISSUE TITLE
Configurable database schema name

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-tractusx/tractusx-edc#311]
**Describe the solution you'd like**

At the time of writing the database schema name, the flyway migration library uses, is not configurable. This means the connector uses the default database schema where it create its tables. Normally this is `public` schema, but might be another schema, too.

There exist deployment environments, where the default schema is not accessible for the EDC and another schema has to be used.

**Additional context** 

As workaround its possible to create a specific database user with a dedicated default schema, the EDC then uses. But a cleaner solution would be a configurable schema name in the EDC itself.

<sub>Dominik Pinsel <dominik.pinsel@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [legal info/Impressum](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md) </sub>

**Comment by bcronin90** [comment]
Please assign to me. Thanks.

**Comment by bcronin90** [comment]
Added the parameter, tested and verified functionality. But where do we document parameters for this extension?

**Comment by florianrusch-zf** [comment]
> Added the parameter, tested and verified functionality. But where do we document parameters for this extension?
In the extension itself? and in the changelog :-)
