### ISSUE TITLE
EDR Management API

### ISSUE THREAD

**Issue by wolf4ood** [eclipse-tractusx/tractusx-edc#330]
##Describe the solution you'd like

Here #321 we are introducing the EDR store/cache for `HttpProxy` transfer process completed. 
We should have some management REST API for interacting with the store like fetching all the EDR negotiated by filtering for

- assetId
- agreementId

**Comment by florianrusch-zf** [comment]
@wolf4ood Why not also the transfer process id? And what do you mean with `contractId`? Do you mean the agreement id?

**Comment by wolf4ood** [comment]
@florianrusch-zf  yes i meant agreemejntId let me change that.  For transfer process id we could have the filter but probably will will have a specific api for retrieving by transfer process id since it will be basically the ID unique of the EDR cached
