### ISSUE TITLE
Implement Data Plane modules for IDS/AAS integration

### ISSUE THREAD

**Issue by jimmarino** [eclipse-tractusx/tractusx-edc#356]
As part of the new IDS/AAS integration planned for the next milestone, we need to implement data plane extensions that support proxying asset requests to a provider. These interactions are defined [here](https://github.com/Metaform/edc-aas)

**Comment by wolf4ood** [comment]
Closed by https://github.com/eclipse-tractusx/tractusx-edc/pull/378
