### ISSUE TITLE
Move `InMemoryVault` to a more generic location

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-tractusx/tractusx-edc#366]
## WHAT

Issue https://github.com/eclipse-edc/Connector/issues/3075 upstreams our `InMemoryVault` to be the default implementation of EDC.
Once the respective PR is merged, we can remove the `InMemoryVault` from our code base and take the one from upstream.

## WHY
Currently our `InMemoryVault` is only available in the deployment tests, but we'd like to have it available in other test environments as well, e.g. e2e tests using the JVM runner. 

## ADDITIONAL NOTES
this issue can be done once https://github.com/eclipse-edc/Connector/issues/3075 is complete.

_Originally posted by @jimmarino in https://github.com/eclipse-tractusx/tractusx-edc/pull/357#discussion_r1196046559_

**Comment by stephanbcbauer** [comment]
memory vault is now in upstream
