### ISSUE TITLE
Integrate code coverage

### ISSUE THREAD

**Issue by wolf4ood** [eclipse-tractusx/tractusx-edc#389]
## Describe the solution you'd like

It would be cool to integrate a coverage tool in the repository and in the PRs workflow

We should have in the main `README` a pointer in the current coverage status and we 
integrate a tool that calculate the impact in coverage diff in PR.

## Describe the solution you'd like

In upstream EDC the combination of Jacoco + Codecov it's used. Probably make sense to use the same
setup

**Comment by paullatzelsperger** [comment]
I'll re-open this, because according to the [documentation](https://docs.sonarcloud.io/advanced-setup/automatic-analysis/), the automatic analysis does not support Code Coverage. 
We therefor have to switch back to CI-triggered analysis. I'll open another PR for that.

**Comment by paullatzelsperger** [comment]
to sum up: we either have automatic Sonar analysis on _every commit_, but we'll have no coverage analysis, or we perform the analysis manually, but only on upstream commits.

Alternatively, we could introduce another tool just for coverage but that seems a bit over-the-top.
