### ISSUE TITLE
Reference links to the Supporting Infrastructure files are outdated.

### ISSUE THREAD

**Issue by MarkAshraf96** [eclipse-tractusx/tractusx-edc#399]
While working on the [Local TXDC Setup.md](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/docs/samples/Local%20TXDC%20Setup.md) I found that the reference links to the Supporting Infrastructure files are outdated and lead to error 404.

<img width="1300" alt="image" src="https://github.com/eclipse-tractusx/tractusx-edc/assets/40201647/c16fd488-1db3-4d03-9c4f-8bbed181ea5c">

**Comment by paullatzelsperger** [comment]
Neither the Local TXDC Document, nor the supporting infrastructure exist anymore.
