### ISSUE TITLE
--update-dependencies flag is unknown

### ISSUE THREAD

**Issue by MarkAshraf96** [eclipse-tractusx/tractusx-edc#403]
Following the [Supporting Infrastructure Deployment](https://github.com/eclipse-tractusx/tractusx-edc/tree/main/edc-tests/deployment/src/main/resources/helm/test-infrastructure) in the setup section there is this command

```shell
helm install infra edc-tests/deployment/src/main/resources/helm/test-infrastructure --update-dependencies
```

but when I try it, I get the error 

```
Error: unknown flag: --update-dependencies
```

**Comment by paullatzelsperger** [comment]
the supporting infrastructure does not exist anymore. Generally though, the flag for the `install` command is called `--dependency-update`
