### ISSUE TITLE
Getting build failed issue while running ./gradlew dockerize

### ISSUE THREAD

**Issue by junaidtk** [eclipse-tractusx/tractusx-edc#507]
## Not able to build the tractusx-edc
While running the below command,
`./gradlew dockerize`
I am getting error like below. I am not able to build the project.

`Task :edc-controlplane:edc-controlplane-memory-hashicorp-vault:dockerize
Building image using context '/Users/junaidtk/Documents/java/eclipse-edc/tractusx-edc/edc-controlplane/edc-controlplane-memory-hashicorp-vault'.
Using Dockerfile '/Users/junaidtk/Documents/java/eclipse-edc/tractusx-edc/edc-controlplane/edc-controlplane-memory-hashicorp-vault/src/main/docker/Dockerfile'
Using images 'edc-controlplane-memory-hashicorp-vault:0.4.2-SNAPSHOT', 'edc-controlplane-memory-hashicorp-vault:latest'.
Step 1/17 : FROM alpine:3.18.0 AS otel
 ---> 44dd6f223004
Step 2/17 : ENV OTEL_AGENT_LOCATION "https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.12.1/opentelemetry-javaagent.jar"
 ---> Using cache
 ---> d9d33d9bfdfe
Step 3/17 : HEALTHCHECK NONE
 ---> Using cache
 ---> 329f7ebfe225
Step 4/17 : RUN apk update && apk add curl=8.1.2-r0 --no-cache
 ---> Using cache
 ---> 4bf500faa200
Step 5/17 : RUN curl -L --proto "=https" -sSf ${OTEL_AGENT_LOCATION} --output /tmp/opentelemetry-javaagent.jar
 ---> Using cache
 ---> 6b970dea01fe
Step 6/17 : FROM eclipse-temurin:17.0.6_10-jre-alpine

> Task :edc-controlplane:edc-controlplane-memory-hashicorp-vault:dockerize FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':edc-controlplane:edc-controlplane-memory-hashicorp-vault:dockerize'.
> Could not build image: no matching manifest for linux/arm64/v8 in the manifest list entries`

What will be exact issue. 

I am using M1 Macbook pro to run the project.

_Steps to reproduce the behavior:_

1. clone the [repo](https://github.com/eclipse-tractusx/tractusx-edc)
2. run the command `./gradlew dockerize`
3. getting error in the command line window.

**Comment by tuncaytunc-zf** [comment]
I don't think this is really a bug, since it work for me locally and for many others too and  as well in CI pipeline.

**Comment by paullatzelsperger** [comment]
This really is not a build problem of EDC. Docker doesn't find any images for your architecture, which is `arm64` (Apple M1). simply append `-Dplatform="linux/amd64"` to your docker command.

**Comment by junaidtk** [comment]
Thanks for the update @paullatzelsperger 
I will check the new command. 
I think the new command will be 
`./gradlew dockerize -Dplatform="linux/amd64"`

I hope it will work fine.

**Comment by junaidtk** [comment]
Very helpful command. I run 
`./gradlew dockerize -Dplatform="linux/amd64"`
It can able to build successfully.
Thanks for the great support.

I need to run a sample connect of eclipse-tractusx with catena x. Do you have any suggestion or any sample suggestion to run on local machine ?
Any helping document or link will be appreciated.

**Comment by paullatzelsperger** [comment]
pls check out `docs/samples`
