### ISSUE TITLE
Replace `HashiCorp` vault implementation with upstream

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-tractusx/tractusx-edc#589]
## WHAT

Remove the Tractusx-EDC impl. of Hashicorp Vault and replace its usage with the one that was upstreamed in https://github.com/eclipse-edc/Connector/issues/3254.

## WHY
no point in having multiple identical impls.

## FURTHER REMARKS

can be done as soon as EDC version `0.1.4` or later is used

**Comment by paullatzelsperger** [comment]
implicitly fixed by #674

**Comment by florianrusch-zf** [comment]
@paullatzelsperger do you know, if this will contain breaking changes in the configuration?
