### ISSUE TITLE
Build: exclude certain modules from publishing

### ISSUE THREAD

**Issue by paullatzelsperger** [eclipse-tractusx/tractusx-edc#603]
## WHAT

Some modules should be excluded from publishing to MavenCentral. This includes all test modules.

The modules we use to generate Docker images (control plane, data plane) produce an `...-all.jar` file ("fat/uber jar"), which we should also exclude.

## WHY

They are not intended for public consumption.

**Comment by florianrusch-zf** [comment]
@paullatzelsperger i think this is still something we should do or?
