### ISSUE TITLE
Participant ID setting on data plane chart configuration

### ISSUE THREAD

**Issue by wolf4ood** [eclipse-tractusx/tractusx-edc#624]
## Describe the bug

The participant ID it's only configured in the control plane chart.

We should add also the configuration in the data plane one

**Comment by florianrusch-zf** [comment]
@wolf4ood could you quick document here, why this is needed?

**Comment by wolf4ood** [comment]
Hi @florianrusch-zf  it is a bug or missing configuration reported in the extended weekly meeting yesterday.
In general it's not needed but the Users is extending the data plane stuff and need a consistent participant id

**Comment by tuncaytunc-zf** [comment]
And there was always a warning like `The runtime is configured as an anonymous participant. DO NOT DO THIS IN PRODUCTION.`
