### ISSUE TITLE
MIW Client Extension: Use participantId as holderIdentifier if present. 

### ISSUE THREAD

**Issue by domreuter** [eclipse-tractusx/tractusx-edc#629]
**Is your feature request related to a problem? Please describe.**
Actually the relation between "holderIdentifier" and "ParticipantId" (connector BPN) is made within the MIW, but can also be provided by the MIW Api Client directly.

We can use the "participantId" if it is present in the actual context, otherwise fallback to the MIW side resolution again.
From my understanding "participantId" is anyway a mandatory setting for the connector used by multiple extensions.

**Describe the solution you'd like**
Within the MIW Api Client the "holderIdentifier" can be resolved from the participantId provided by the actual context.

**Comment by paullatzelsperger** [comment]
A VC can only ever be obtained for oneself, never for anyone else, therefore the `holderIdentifier` parameter is pointless. That means, there can never be a (valid) value for the `holderIdentifier` parameter, thus it's spurious.

**Comment by domreuter** [comment]
> Hi @domreuter can you explain a little bit more why you need this?
> 
> also AFAIK the MIW does not support the `holderIdentifier` parameters in the `getCredentials` request, which is implicitly derived by the Authentication token

Referring to the MIW API the "holderIdentifier" is marked as a required Query-Param.

https://managed-identity-wallets.int.demo.catena-x.net/docs#tag/VerifiableCredentials/

Providing the Id that way will help us building up a java ssi mock application following the MIW api.

**Comment by wolf4ood** [comment]
Hi @domreuter 

i think that's is the old MIW, the new one is located here

https://managed-identity-wallets-new.int.demo.catena-x.net/ui/swagger-ui/index.html#/Verifiable%20Credential%20-%20Holder/getCredentials

we are using the `Holder` get gredentials API call


Thanks

**Comment by domreuter** [comment]
I was not aware that there is a new version of the api available.

Expecting the next increment to be https://managed-identity-wallets-newest.int.demo.catena-x.net then. ;-)

I will retrieve then the holderIdentifier from the token, think thats the way to do it with the "new" api then.

@wolf4ood Thanks for keeping me up-to-date, will close the Issue then.

**Comment by domreuter** [comment]
Missed following the new api for MIW.
