### ISSUE TITLE
SSI - Big Picture and Roadmap (ext: CXAR-1035)

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/tractusx-edc#657]
+*Benefit Hypothesis*+
< What´s the purpose, what´s the expected result. You can use User Story Format and Gherkin or following simple approach: If (proposition), then (benefit)>

 

+*Beneficiaries*+
< Who will benefit for that feature>

 
Subtasks:
- [x] #654 
- [x] #652 
- [x] #650
- [x] #655 
- [x] #651 
- [x] #649 
- [x] #656

_Components_: CPLP, EDC, MIW
_Sprints_: N/A
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: N/A

**Comment by benwestphal** [comment]
Prob more info after SSI Workshop
