### ISSUE TITLE
EDC - Connector KIT Documentation & Support MVD (ext: CXAR-1034)

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/tractusx-edc#658]
+*Benefit Hypothesis*+
Right now for every catena-x release the files needs to be copied from tractusx-edc repository to tractusx.github.io repository → it's done manually. I would like to have a better way here. A lot of user are asking for a manual to build/play with a data space. Its not the responsible for only one team (edc/miw/...) → it should be joint work to build such a documentation. Maybe like the old catenax@home
 

+*Beneficiaries*+
< Who will benefit for that feature>

 

_Components_: EDC
_Sprints_: N/A
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: N/A

**Comment by stefan-ettl** [comment]
Tasks
- [ ] Improve the process of KIT Documentation.
- [ ] Decide about using Autodoc
- [ ] Update to the current version.
- [ ] Create the tutorial (Documentation) for the MXD/MVD: https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/313
- [ ] Run the Setup at your machine locally and give feedback.
- [ ] Adding Features to the existing Setup.

**Comment by paullatzelsperger** [comment]
related: https://github.com/eclipse-tractusx/tutorial-resources/issues/34 and https://github.com/eclipse-tractusx/tutorial-resources/issues/26

**Comment by stephanbcbauer** [comment]
@stefan-ettl 

- **Autodoc** seems to be also ok, cause the related Issue was already closed https://github.com/eclipse-tractusx/tractusx-edc/issues/700
- *Update the current version** means the Connector Kit. Last updates were made in August. But maybe we can use the time in PI 11 and do the restructuring => https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/discussions/448
- **Run the setup** if we are talking about the [E2E Adopter Journey tutorial ](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/tree/feat/tutorials/docs/tutorials) => test was done by Johannes D and myself

**Comment by ndr-brt** [comment]
> * **Autodoc** seems to be also ok, cause the related Issue was already closed [docs: Autodoc generation/preperation #700](https://github.com/eclipse-tractusx/tractusx-edc/issues/700) => but question is still... can we use it? Is the created JSON also transferred to markdown?

The autodoc json is [generated and converted to markdown](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/.github/workflows/publish-docusaurus.yaml#L60-L64) then [put in the Devlopment View/05_EDC extensions folder](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/resources/create_kit_documentation.sh#L42)

**Comment by stephanbcbauer** [comment]
> > * **Autodoc** seems to be also ok, cause the related Issue was already closed [docs: Autodoc generation/preperation #700](https://github.com/eclipse-tractusx/tractusx-edc/issues/700) => but question is still... can we use it? Is the created JSON also transferred to markdown?
> 
> The autodoc json is [generated and converted to markdown](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/.github/workflows/publish-docusaurus.yaml#L60-L64) then [put in the Devlopment View/05_EDC extensions folder](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/resources/create_kit_documentation.sh#L42)

Not sure what to do with this issue :( i think documentation is helpfull somewhere... initial idea was the kits... but since the process changed (also the mentioned [put in the Devlopment View/05_EDC extensions folder](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/resources/create_kit_documentation.sh#L42) is not needed anymore... i am not sure if the output fits to the new structure of the connector kit. what do you think? @bcronin90 

For kits there is also the possibility to hvae a documentation section. We also had this initialy...

**Comment by arnoweiss** [comment]
@stefan-ettl  - I think this can be closed with the merge of https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/558
