### ISSUE TITLE
EDC - Revise Multi-Tenancy PR  (ext: CXAR-1033)

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/tractusx-edc#659]
+*Benefit Hypothesis*+
< What´s the purpose, what´s the expected result. You can use User Story Format and Gherkin or following simple approach: If (proposition), then (benefit)>

 

+*Beneficiaries*+
< Who will benefit for that feature>

 

_Components_: EDC
_Sprints_: N/A
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: N/A

**Comment by stefan-ettl** [comment]
Review based on old PR: https://github.com/catenax-ng/product-edc/pull/477

**Comment by stefan-ettl** [comment]
Tasks
- [ ] Revise and update the PR for TractusX-EDC.
- [ ] Document the MT approach.

**Comment by paullatzelsperger** [comment]
sample: https://github.com/eclipse-tractusx/tractusx-edc/tree/main/samples/multi-tenancy
