### ISSUE TITLE
EDC - Execute Performance Tests (ext: CXAR-1032)

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/tractusx-edc#660]
+*Benefit Hypothesis*+
Currently we have no reliable / repeatable performance tests. A story was planned but could not be executed so far A1IDSC-422 - EDC - Execute Performance TestsIN PROGRESS

Based on this performance improvements might be triggered in the next PI

 

+*Beneficiaries*+
< Who will benefit for that feature>

 

_Components_: EDC
_Sprints_: N/A
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: N/A

**Comment by stefan-ettl** [comment]
Tasks
- [ ] Document the results. 
- [ ] Update/Revise the initial draft.

**Comment by benwestphal** [comment]
Being worked on but other topics have higher priority right now.
@hemantxpatel is in the loop and can give updates about the topic

**Comment by stefan-ettl** [comment]
Move to PI11

**Comment by alexandrudanciu** [comment]
This is the overall status of the performance evaluation:
- [X] Documentation 
- [X] Automated test driver based on JMeter
- [ ] Review of experiment design
- [ ] Measurement on Hotel Budapest

**Comment by hemantxpatel** [comment]
Currently it is under a repo into @alexandrudanciu's personal account, https://github.com/alexandrudanciu/mxd-performance-evaluation.
We will move it to a centralized repo soon.
