### ISSUE TITLE
EDC - Interoperability between S3 and Azure Blob Protocols (ext: CXAR-1031)

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/tractusx-edc#661]
+*Benefit Hypothesis*+
Current situation:
All participant need to have all protocols, even if they're not using the technology by themselves. Today Azure Blob is not included in Tracuts-X EDC.
Decision needed how to continue with both technologies. 
 

+*Beneficiaries*+
< Who will benefit for that feature>

 

_Components_: EDC
_Sprints_: N/A
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: N/A

**Comment by stefan-ettl** [comment]
Tasks
- [ ] Define a list of supported protocols.
- [ ] Create a concept for context/Use-Case specific protocols or adoptions.
- [ ] Answer the question of how to deal with vendor specific solutions (S3 & Blob)?

**Comment by paullatzelsperger** [comment]
questions: 
- is it sufficient to have a one-size-fits-all dataplane? 
- is this limited to object storage (as opposed to: vaults, databases,....)?

we'll have to work out various options first and collect requirements.

**Comment by benwestphal** [comment]
@paullatzelsperger is on the task
final implementation in 0.6 due to impacts
