### ISSUE TITLE
EDC - Control Plane Improvements (ext: CXAR-1029)

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/tractusx-edc#663]
+*Benefit Hypothesis*+
*  Subsumption of negotiated constraints
*  Additional runtime properties
*  Alignment of Agent Federated Catalog and EDC Fed. Catalogue

 

+*Beneficiaries*+
< Who will benefit for that feature>

 

_Components_: EDC
_Sprints_: N/A
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: N/A

**Comment by stefan-ettl** [comment]
@ndr-brt any update regarding the runtime properties?

**Comment by ndr-brt** [comment]
@stefan-ettl already implemented upstream within https://github.com/eclipse-edc/Connector/pull/3277/files

timeouts on the http client can be configured with:
- `edc.http.client.timeout.connect`
- `edc.http.client.timeout.read`

**Comment by benwestphal** [comment]
@gerbigf will contact Marc Gerstner about further information/ better ticket description
