### ISSUE TITLE
EDC - Notification Service for Broadcasting (ext: CXAR-1010)

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/tractusx-edc#664]
+*Benefit Hypothesis*+
In Rel. 3.3 we need to implement the capability to add submodels to existing material twins (or even complete material twins), when a PCF is requested for a part, for which no corresponding submodel (or even twin) exists. The call Client => PCF app is fine, but we do NOT want the PCF App to directly write into a dDTR hosted somewhere else (tight coupling). Therefor we would like to go for an observer pattern based approach (loose coupling):

Together with our PCF Exchange asset we would also offer a (PCF) Event asset
Tenants using our app and hosting their own dDTR can register for PCF Events
The PCF App emits an event when a PCF for a part is created
The tenant is listening on this event and adding a corresponding subodel (or even twin) into its dDTR if needed

[~werner.eberling.ext@evosoft.com](~werner.eberling.ext@evosoft.com) ???
 

+*Beneficiaries*+
< Who will benefit for that feature>

 

_Components_: EDC
_Sprints_: N/A
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: N/A

**Comment by benwestphal** [comment]
@paullatzelsperger please close

**Comment by paullatzelsperger** [comment]
The question has been answered in the description - basically create an asset that serves as event source
