### ISSUE TITLE
Define & document process for adoption requests in Tractus-X  (ext: CXAR-1008)

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/tractusx-edc#666]
+*Benefit Hypothesis*+
Define and document process to enable teams outside EDC team to contribute and deliver additional capabilities: 
https://github.com/eclipse-edc/.github/blob/main/.github/ISSUE_TEMPLATE/adoption_request.md#adoption-in-edc-core
 

+*Beneficiaries*+
< Who will benefit for that feature>

 

_Components_: EDC
_Sprints_: N/A
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: N/A

**Comment by stefan-ettl** [comment]
Tasks
- [ ] Document the Process for creating an adoption request.
- [ ] Take over the template from upstream EDC.
