### ISSUE TITLE
EDC - Extended Workflows (manual approval) (ext: CXAR-980)

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/tractusx-edc#667]
*Benefit Hypothesis*
Manual interceptions of Statemachines (i.e. onboarding/ off boarding):
 * no restrictions defined in regards to access/ see contract offers
 * in case of an unknown consumer during contract definition creation, it should be possible to approve the contract manually when a negotiation has been started by one specific data consumer
 * Configuration of a Manual interaction by creating the Contract Offer.

+*Benefit Hypothesis*+
< What´s the purpose, what´s the expected result. You can use User Story Format and Gherkin or following simple approach: If (proposition), then (benefit)>

 
 

_Components_: EDC
_Sprints_: N/A
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: N/A

**Comment by benwestphal** [comment]
@gerbigf contact Markus Hauser about actual requirements

**Comment by stefan-ettl** [comment]
Not Requested.
