### ISSUE TITLE
EDC - Gateway Process incl. Security und Hotfixes (ext: CXAR-979)

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/tractusx-edc#668]
+*Benefit Hypothesis*+
* Prepare Q-Gates
* Prepare Security Scans & Fixes
 

+*Beneficiaries*+
< Who will benefit for that feature>

 

_Components_: EDC
_Sprints_: N/A
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: N/A

**Comment by stefan-ettl** [comment]
Tasks
- [ ] Triggering the System Team to create the issue.
- [ ] Complete Q-Gate Tasks (manual work).
- [ ] Update Github Actions for Sec Tools if necessary.

**Comment by benwestphal** [comment]
can be closed ? @stefan-ettl
