### ISSUE TITLE
Sychronize agreements between EDC instances of one given partner (ext: CXAR-977)

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/tractusx-edc#669]
{color:#de350b}check with governance / policy kit{color}

 

+*Benefit Hypothesis*+
< What´s the purpose, what´s the expected result. You can use User Story Format and Gherkin or following simple approach: If (proposition), then (benefit)>

 

+*Beneficiaries*+
< Who will benefit for that feature>

 

_Components_: EDC
_Sprints_: N/A
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: N/A

**Comment by benwestphal** [comment]
@gerbigf please contact Markus Hauser about the requirements

**Comment by stefan-ettl** [comment]
Feature unclear
