### ISSUE TITLE
Concept for Upgradeability for EDC (ext: CXAR-901)

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/tractusx-edc#670]
*Background:*

Current Product EDC is still in a phase of continuous development which leads to frequent enhancements and changes between subsequent versions. One of the reasons for this status is that IDSA protocol (which is the base for the EDC) is still in progress/ definition phase (current version 0.8) and has no official released version. Consequently, this status forces regular, major changes to EDC which are not compatible to previous EDC versions. The effort for data providers/ data consumers updating there connector is currently significant and causes delays in EDC deployment. In addition, different EDC versions lead to incompatibility issues when participants are transferring data using different EDC versions. This situation slows down the scalability of Catena-X network.

*Benefit Hypothesis:*
A concept is required which supports companies which are using EDC to enable a smoother and faster update process and allows better scalability of Catena-X network.

*Short description:*

To bridge time until IDSA protocol version 1.0 is released a concept is required which:
 * offers a step-by-step guide to upgrade EDC
 * provides guardrails for data providers/ data consumers
 * describe general framework to configure and set-up EDC in an optimized way
 * Leverage automated documentation creation from EDC
*  EDC compatibility check before creating a contract offer

_Components_: EDC
_Sprints_: N/A
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: N/A

**Comment by stefan-ettl** [comment]
Different dimensions
- [ ] SemVer - document the current approach.
- [ ] Answer/Define the term compatibility of EDCs.
- [ ] Concept for compatibility and its dependencies. (Goes beyond EDC, i.e. MIW - consistence voc. across the products)
- [ ] Compatibility check between EDCs (define what counts into it like Policies, Extensions, ...)
- [ ] Answer/Define the term Backwards Compatibility.
- [ ] Create rules compatibility of versions.

**Comment by gerbigf** [comment]
After a chat with an enterprise architect I learned that this requirement comes from Stefan, thus maybe being a requirement from consortia lead. I wasn't able to identify a stakeholder that can give us requirements.

**Comment by stefan-ettl** [comment]
Continue with Features in PI11
