### ISSUE TITLE
Latest `0.5.0` release contains restricted dependencies

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/tractusx-edc#721]
## Describe the bug

The `DEPENDENCIES` file in the [latest release tag](https://github.com/eclipse-tractusx/tractusx-edc/blob/0.5.0_rn/DEPENDENCIES#L212) does contain two restricted libraries. It seems, that there hasn't been license information available, for that specific version of the dependencies at the time the file was created. 

### To Reproduce

N/A

### Expected behavior

Creating a release should only be done, when there are no `restricted` or `rejected` dependencies present in the `DEPENDENCIES` fiel. The file has to be up-do-date of course.

### Screenshots/Error Messages

N/A

## Context Informations

blocking Quality Gate #714 

## Possible Implementation

re-running the [Dash license tool](https://github.com/eclipse/dash-licenses)

**Comment by SebastianBezold** [comment]
The newly created release `0.5.1` does only contain "approved" libs now. 

What I am unsure about is, if we need to still fix the `DEPENDENCIES` file for `0.5.0`
@AngelikaWittek could you provide some insights on that?

**Comment by SebastianBezold** [comment]
As I understood, creating a bugfix release with updated dependencies is fine here, right @AngelikaWittek?
Therefore I will close the issue, but still hope, that future release will only be created with approved libs :)

**Comment by wolf4ood** [comment]
@SebastianBezold  since this is closed can i mark the [TRG 7.04](https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-04) in #714  done?

Thanks

**Comment by SebastianBezold** [comment]
Oh yes, just checked the TRG even though the issue is already closed
