### ISSUE TITLE
Add a static `CHANGELOG.md` containing the release history

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/tractusx-edc#723]
**Is your feature request related to a problem? Please describe.**
[TRG 1.03](https://eclipse-tractusx.github.io/docs/release/trg-1/trg-1-3) describes, that every Tractus-X repo must contain a `CHANGELOG.md` file, that contains a short overview of the current and past releases. 
The info present on the GitHub releases like for example on [0.5.0](https://github.com/eclipse-tractusx/tractusx-edc/releases/tag/0.5.0_rn) is really good. It can be used "as-is" in the `CHANGELOG.md` as well.

**Describe the solution you'd like**
As far as I can remember, there has been a `CHANGELOG.md` for the Tractus-X EDC in the past. If this can still be found, I think it should be added again and the current `0.5.0` release info added as well.

**Describe alternatives you've considered**
Replacing the `CHANGELOG.md` by just having the change description on the GitHub release would remove the possibility to browse easily through the release history. One would have to go through all of the GitHub releases (also RCs), which is just not as convenient as having it in one place

**Additional context**
_Add any other context or screenshots about the feature request here._

blocks #714

**Comment by dsukhoroslov** [comment]
it was removed intentionally, AFAIK: https://github.com/eclipse-tractusx/tractusx-edc/blob/0.5.1/docs/development/decision-records/2023-07-06_removing_manual_changelog/README.md

**Comment by SebastianBezold** [comment]
Hi @dsukhoroslov, thanks for pointing that out. So it seems, the `CHANGELOG.md` will be added again. This is a good thing, because the decision is actually violating the project rules (which is the release Guidelines). So I hope this is not too much effort. The auto-generated release notes on a GitHub release seem quite well structured, so I think they can just be copy/pasted to the `CHANGELOG`, so the release history is continued

**Comment by wolf4ood** [comment]
closed by https://github.com/eclipse-tractusx/tractusx-edc/pull/733
