### ISSUE TITLE
SsiMiwOauth2ClientExtension: Error message can be confusing

### ISSUE THREAD

**Issue by awellnitz-materna** [eclipse-tractusx/tractusx-edc#777]
In the following line, developers can quickly become confused. 
https://github.com/eclipse-tractusx/tractusx-edc/blob/7362ca1ee8d375a82ef6198847fa30eff65e5280/edc-extensions/ssi/ssi-miw-credential-client/src/main/java/org/eclipse/tractusx/edc/iam/ssi/miw/SsiMiwOauth2ClientExtension.java#L70

I believe a more suitable message would be as follows: `Client secret could not be retrieved`.
With the message that the secret could not be found, you can also think that you may not have created it correctly.

But even if the client has no permissions, the same message appears.
Of course, you could solve this more elegantly with error handling, but this must happen in the upstream repo.

**Comment by wolf4ood** [comment]
Hi @awellnitz-materna 

that make sense, can you provide a PR for this?

Thanks
