### ISSUE TITLE
AWS S3 transfer stays in started state

### ISSUE THREAD

**Issue by lucian-torje-siemens** [eclipse-tractusx/tractusx-edc#790]
## Describe the bug

Even if the AWS S3 file transfer is successful, the state remains started.

### To Reproduce

_Steps to reproduce the behavior:_

1. negotiate contract on AWS S3 asset
2. start transfer to AWS S3 with managedResource true/false (does not matter)

### Expected behavior

State transitions to completed (800)

### Current behavior

State transitions to started (600)

## Context Information

- Used version: tractus EDC 0.5.1

tractusx/edc-dataplane-hashicorp-vault                                       0.5.1                                      36b7650f3eb6   4 weeks ago     231MB
tractusx/edc-controlplane-postgresql-hashicorp-vault                         0.5.1                                      37ed2a193895   4 weeks ago     244MB

## Possible Implementation

Add https://[oss.sonatype.org/service/local/repositories/releases/content/org/eclipse/edc/provision-aws-s3/0.2.1/provision-aws-s3-0.2.1.pom](https://oss.sonatype.org/service/local/repositories/releases/content/org/eclipse/edc/provision-aws-s3/0.2.1/provision-aws-s3-0.2.1.pom) as  a dependency.

> **_NOTE:_** There are plans to remove the status checker in EDC https://github.com/eclipse-edc/Connector/issues/3448

## Related

see https://github.com/eclipse-edc/Connector/issues/3334

**Comment by wolf4ood** [comment]
Hi @lucian-torje-siemens 

thanks for raising this. This issue has been fixed in upstream EDC in mentioned PRs in the related issue, and it will be incorportated in tractusx-edc once this is merge.

https://github.com/eclipse-tractusx/tractusx-edc/pull/782

Thanks
