### ISSUE TITLE
No checker found for process - unending loop

### ISSUE THREAD

**Issue by arunsworld** [eclipse-tractusx/tractusx-edc#799]
## Describe the bug

When a transfer is initiated the state model on the consumer side is stuck in Started with no hope of reaching the next Completed stage due to absence of a checker.

In this instance HttpProxy was used and the logs show:
No checker found for process 6ffc948e-d583-4ed5-a7c8-92212a46ffa9. The process will not advance to the COMPLETED state.

Should there not be some default implementations even if a Noop to move the process along? This infinite loop appears to be using up increasing amount of resources as transfer requests pile up.

### To Reproduce

After contract negotiation, invoke /v2/transferprocess to initiate a transfer with dataDestination as HttpProxy.

### Expected behavior

Once the EDR is transmitted, the state should transition to Completed.

### Screenshots/Error Messages

No checker found for process 6ffc948e-d583-4ed5-a7c8-92212a46ffa9. The process will not advance to the COMPLETED state.

## Context Information

Used version: sha-4b38aa4
tractusx/edc-controlplane-postgresql-hashicorp-vault:sha-4b38aa4

## Possible Implementation

Suggest either removing the checker if redundant or adding appropriate checkers for HttpProxy and any other standard dataDestinations even if Noops

**Comment by wolf4ood** [comment]
Hi @arunsworld 

thanks for raising this issue. The fix has already been applied in upstream EDC see [here](https://github.com/eclipse-edc/Connector/issues/3448). It will be available in the next EDC release 0.3.1 and then incorporated in tractusx-edc

Thanks

**Comment by arunsworld** [comment]
Thanks for the prompt update, much appreciated.
