### ISSUE TITLE
EDR-Cache Extension: Add ability to store tokens in specific Vault folder

### ISSUE THREAD

**Issue by awellnitz-materna** [eclipse-tractusx/tractusx-edc#800]
## WHAT

The EDR-Cache Extension should be able to store EDR tokens in a Vault folder.

## WHY

If no folder can be specified and the tokens are written to the "main" vault folder of the service, it can be difficult to keep track of them.
![Vault EDR Tokens](https://i.imgur.com/mN8wsje.png)

## HOW

A new string parameter should be passed to the constructor. By default, this parameter should be empty. If it is not empty, a folder can be specified.

```java
    public static final String SEPARATOR = "--";
    private final String vaultPath;
    public final String vaultPrefix;
    ...
    
    this.vaultPrefix = vaultPath + "edr" + SEPARATOR;
    ...
    
    cache = new SqlEndpointDataReferenceCache(extension.getDataSourceRegistry(), extension.getDatasourceName(), "edr-cache/", extension.getTransactionContext(), statements, typeManager.getMapper(), vault, clock, queryExecutor, CONNECTOR_NAME);
```

**Comment by wolf4ood** [comment]
Hi @awellnitz-materna 

thanks for raising this, it will be definitely a nice addition.

**Comment by awellnitz-materna** [comment]
@wolf4ood 
Yes I already use the 0.5.1. 
You are right that the tokens are deleted but once you have a few 1000 tokens, it still gets confusing 😄
