### ISSUE TITLE
Make JSON-LD contexts configurable

### ISSUE THREAD

**Issue by ronjaquensel** [eclipse-tractusx/tractusx-edc#830]
## WHAT

In the `JsonLdExtension`, the context URIs and corresponding JSON-LD files for credentials and security are defined at the code level, i.e. they are hardcoded. These should be configurable to allow the usage of different contexts/URIs without the need for additional extensions.

## WHY

To allow for more flexibility regarding the used contexts. If any changes need to be made to the used contexts (e.g. to connect to an MIW using different contexts), this is currently only possible by adding additional extensions/rebuilding the EDC. 

## HOW

Make the URIs and paths to load the files from configurable in the `JsonLdExtension`, keeping the existing values as fallback in case no respective configuration is provided.

**Comment by wolf4ood** [comment]
Hi @ronjaquensel 

AFAIK this is possible with the `JsonLdExtension` of EDC upstream right?

https://github.com/wolf4ood/DataSpaceConnector/blob/main/extensions/common/json-ld/src/main/java/org/eclipse/edc/jsonld/JsonLdExtension.java#L102

Does this solve this issue?

Thanks

**Comment by ronjaquensel** [comment]
Hi @wolf4ood,

this solution works fine for loading contexts that define things not yet present in the fixed contexts. In our case we need to provide our own contexts defining the same things already included in the fixed contexts (e.g. the summary credential).

When loading additional contexts that define the same things already present in one of the registered contexts, this leads to an error in the titanium library. Therefore, we'd need a way to completely **replace** the contexts from the `JsonLdExtension`, so that only our contexts are loaded. 

Best regards

**Comment by wolf4ood** [comment]
So you don't want to configure additional context you want to override the summary credential one right?

**Comment by wolf4ood** [comment]
Do you have an example or a link on how this override would look like?

Thanks
