### ISSUE TITLE
Build and dockerize the project under windows 

### ISSUE THREAD

**Issue by mustafasalfiti** [eclipse-tractusx/tractusx-edc#853]
using ./gradlew dockerize under windows will lead to a confusion inside the Dockerfile
because how paths are handled in windows 

for example running the current command in windows 

`./gradlew.bat :edc-controlplane:edc-controlplane-memory-hashicorp-vault:dockerize
`

will lead into this error

```

> Task :edc-controlplane:edc-controlplane-memory-hashicorp-vault:dockerize FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':edc-controlplane:edc-controlplane-memory-hashicorp-vault:dockerize'.
> Could not build image: COPY failed: file not found in build context or excluded by .dockerignore: stat build\opentelemetry-javaagent.jar: file does not exist


```

### Expected behavior

to successfuly build the code

### Screenshots/Error Messages

![image](https://github.com/eclipse-tractusx/tractusx-edc/assets/49871916/700157fe-4355-4d0c-bcbd-1c18067cab59)

_Add any other context or information about the problem here._

- Used version: release/0.5.1
- OS: Windows
- Docker Version: 24.0.5

## Possible Implementation

replace the (windows slashes) in the build.gradle.kts for OTEL_JAR to make it work inside the Dockerfile

**Comment by paullatzelsperger** [comment]
The dockerfile is intended for our build process, which runs on Linux.  The official deliverable of tx-edc is a helm chart plus the prebuilt images. Why do you need to build your own connector image, and why do you need the dockerfile for that to be hosted in the tx-edc repository (as opposed to: your own infrastructure)?
