### ISSUE TITLE
Compatibility check / Versioning

### ISSUE THREAD

**Issue by tobzahn** [eclipse-tractusx/tractusx-edc#864]
## WHAT
When connecting to a partner company, we need to ensure that our EDC and the EDC of our partner company are compatible. For this, the EDCs need to check during the connection phase if they support the same protocol versions  and features. If they are not compatible, the connection cannot be established. In a future version, the EDCs could negotiate the protocol version to be used.

## WHY
Without this feature, the connection with old/outdated EDC versions will fail with arbitrary errors. Therefore, without this feature the EDC can never be changed in an incompatible way, new features cannot be added. However, new features will be required at some point.
If an incompatible change is included nevertheless, the data exchange between some partner companies will not be possible anymore, leading to a break of the network.

## HOW
During the connection phase between 2 EDCs, the EDCs need to check if they support/use the same protocol versions. Everything that is required for compatibility needs to be checked during this phase.
If compatibility has been checked successfully, the connection can be established. If not, the connection needs to be terminated with an appropriate error message. In a future version, a version negotiation mechanism can be implemented.

## FURTHER NOTES
As a best case, a version negotiation is offered from the beginning, but it can be seen as optional. 
The Catena-X use cases will need to ensure compatibility for the APIs used on top of what is described here.

**Comment by tobzahn** [comment]
@wolf4ood any comment why this issue was closed?

**Comment by wolf4ood** [comment]
Hi @tobzahn, it was closed automatically by the stale bot. let me re-open it

**Comment by ndr-brt** [comment]
The issue here in fact has (at least not for now) no effort to be spent in this project, because it is currently under discussion in the IDS round and the implementation will be made in the upstream EDC project. 
we can keep this issue open as a reminder (maybe adding a label that stops the stalebot from ignite) but seen the number of people/projects involved I guess it won't be forgotten :)
