### ISSUE TITLE
deprecated WEB_HTTP_IDS_PORT in memory chart

### ISSUE THREAD

**Issue by KilianHaag** [eclipse-tractusx/tractusx-edc#875]
## The deprecated WEB_HTTP_IDS_PORT is still in the "memory" chart

The "memory" chart sets the two environment variables:
WEB_HTTP_IDS_PORT
WEB_HTTP_IDS_PATH

This causes an unreachable /api/v1/dsp endpoint, making the EDC unreachable for other EDCs.

### To Reproduce

Install the "in-memory" chart with default values
Try to query the catalog from another EDC.
![image](https://github.com/eclipse-tractusx/tractusx-edc/assets/124401943/0f5fc52b-589a-40b7-8802-7309261ae648)

### Expected behavior

The deployed EDC has a reachable /api/v1/dsp endpoint.

## Context Information
- Used version: 0.5.1 - 0.5.3

## Possible Implementation
Replace
WEB_HTTP_IDS_PORT
WEB_HTTP_IDS_PATH

with
WEB_HTTP_PROTOCOL_PORT
WEB_HTTP_PROTOCOL_PATH

in
https://github.com/eclipse-tractusx/tractusx-edc/blob/main/charts/tractusx-connector-memory/templates/deployment-runtime.yaml

**Comment by wolf4ood** [comment]
Hi @KilianHaag 

thanks for raising this issue, in case are you able to provide a PR for this issue? :)
