### ISSUE TITLE
In helm chart config, unable to use secret for postgres password

### ISSUE THREAD

**Issue by sabarishrl** [eclipse-tractusx/tractusx-edc#880]
## WHAT
We want to use secrets for postgres db password instead of using the plain text with helm chart config. Currently postgresql.auth.password is mandatory as well.

## WHY
For best security practice, passwords should not be in plain text and part of configs
## HOW

Remove the mandatory check on postgresql.auth.password when secret is provided.

**Comment by paullatzelsperger** [comment]
Hey @sabarishrl we are aware of this, however we will need to implement this in upstream EDC as part of a broader issue: https://github.com/eclipse-edc/Connector/issues/3712

**Comment by sabarishrl** [comment]
Thanks @paullatzelsperger , do we have any approximate release date for this? Can we align this to a particular release? What it takes us to contribute for such issues?
