### ISSUE TITLE
Trivy image scan result are not getting uploaded to GitHub

### ISSUE THREAD

**Issue by tuncaytunc-zf** [eclipse-tractusx/tractusx-edc#882]
## Describe the bug

The Trivy scan reports for image scans are not getting uploaded to GitHub. 

### To Reproduce
The reports are not listed in Security tab

### Expected behavior

All the Trivy scan results should be uploaded to GitHub

## Context Information

Uploading the report for `trivy-analyze-config` seems to work, because there is no failure in GitHub action logs. 
But the reports for the image scans are not marked as successful in GitHub actions and are not visible in Security. So maybe there is something wrong in `trivy` job in trivy.aml file where the image scans and result upload happens.

**Comment by ndr-brt** [comment]
This was resolved for the last QG
