### ISSUE TITLE
Can create policy without `action` which leads to broken fetch all policies with `policiydefinitions/request`

### ISSUE THREAD

**Issue by matgnt** [eclipse-tractusx/tractusx-edc#883]
When someone creates a wrong policy, e.g. with a missing `action` field, thereafter all queries to get a list of policies fails.

[test_policies_no_action_error.txt](https://github.com/eclipse-tractusx/tractusx-edc/files/13462062/test_policies_no_action_error.txt)
[test_policies_no_action.json](https://github.com/eclipse-tractusx/tractusx-edc/files/13462063/test_policies_no_action.json)

Examples attached.

This seems to be very similar to the bug we once had with breaking the catalog with a single wrong item - at least from an outside perspective.

Tested with 0.5.1

Expected behavior:
Invalid policies can not be created. And as backup, the listing should only not include the broken policy, but still be able to query the valid ones.

--
Matthias Binzer

**Comment by wolf4ood** [comment]
Hi @matgnt 

thanks for raising this, I checked also with the latest tx-edc release which pulls upstream EDC version `0.4.1` and this issue is still there. 

Probably make sense to move this issue in upstream EDC,

Thanks

**Comment by ndr-brt** [comment]
On upstream the `Policy` [object is still not validated](https://github.com/eclipse-edc/Connector/blob/a3ef0f16e8aa585b4782de3215e6968ed6168d64/extensions/control-plane/api/management-api/policy-definition-api/src/main/java/org/eclipse/edc/connector/api/management/policy/validation/PolicyDefinitionValidator.java#L25) this could be a good motivation to do so.

**Comment by saschaisele-zf** [comment]
Upstream issue has been closed, so I will do the same here.

**Comment by matgnt** [comment]
@saschaisele-zf before you close the issue, can you please let us know in which tractusx-edc version this fix will be included?

**Comment by saschaisele-zf** [comment]
The upstream changes will be included with the next tractusx-edc release.
So either 0.6.1 or 0.7.0.
