### ISSUE TITLE
contract-spi version mismatch

### ISSUE THREAD

**Issue by maciej-kizlich** [eclipse-tractusx/tractusx-edc#907]
## Describe the bug

EDC version 0.5.3 uses contract-spi in version 0.2.1, which makes contract negotiations fail with:

java.lang.NoSuchMethodError: 'org.eclipse.edc.spi.result.StoreResult org.eclipse.edc.connector.contract.spi.negotiation.store.ContractNegotiationStore.findByCorrelationIdAndLease(java.lang.String)'

since this method was introduced in contract-spi 0.3.0

### To Reproduce

Try to negotiate a contract

### Expected behavior

Contract should be negotiated

### Screenshots/Error Messages

java.lang.NoSuchMethodError: 'org.eclipse.edc.spi.result.StoreResult org.eclipse.edc.connector.contract.spi.negotiation.store.ContractNegotiationStore.findByCorrelationIdAndLease(java.lang.String)'

**Comment by florianrusch-zf** [comment]
As @wolf4ood asked in the matrix chat, this is how our `build.gradle.kts` looks like: 

```kotlin
plugins {
    id("application")
    id("com.github.johnrengelman.shadow") version "7.1.2"
}

dependencies {
    implementation("org.eclipse.tractusx.edc:edc-controlplane-postgresql-hashicorp-vault:0.5.3") {
        exclude(group = "org.eclipse.edc", module = "vault-hashicorp")
    }

    implementation(project(":zf-edc-hashicorp-vault"))
}

application {
    mainClass.set("org.eclipse.edc.boot.system.runtime.BaseRuntime")
}

tasks.withType<com.github.jengelman.gradle.plugins.shadow.tasks.ShadowJar> {
    mergeServiceFiles()
    archiveFileName.set("zf-edc-controlplane.jar")
}

description = "zf-edc-controlplane"
```

Dataplane looks basically the same. The only thing we changed basically is that we replace the hashicorp vault extension with our own. Be basically copied the official one and switched just the auth method for vault to use the kubernetes auth method. The build gradle for our vault extensions look like this:

```kotlin
plugins {
    id("io.freefair.lombok") version "6.6.1"
}

dependencies {
    implementation("org.eclipse.edc:core-spi:0.3.1")

    implementation("org.bouncycastle:bcpkix-jdk18on:1.76")
    implementation("com.squareup.okhttp3:okhttp:4.12.0")

    testImplementation("org.junit.jupiter:junit-jupiter:5.10.0")
    testImplementation("org.mockito:mockito-core:5.2.0")
    testImplementation("org.mockito:mockito-inline:5.2.0")
    testImplementation("org.testcontainers:junit-jupiter:1.19.1")
    testImplementation("org.testcontainers:vault:1.19.1")
    testImplementation("org.eclipse.edc:junit:0.3.1")
}

tasks.withType<Test> {
    useJUnitPlatform()
}

description = "zf-edc-hashicorp-vault"
```

**Comment by wolf4ood** [comment]
Hi @florianrusch-zf 

tractusx edc `0.5.3` depends on edc upstream `0.2.1`, so i think if you pull `core-spi:0.3.1`, that might cause the issue. 


Could you try to change it to and check if the issue persists?

```kotlin
implementation("org.eclipse.edc:core-spi:0.2.1")
```

**Comment by florianrusch-zf** [comment]
Goooood catch! Don't know, why we choose 0.3.1 🤔
Will give it try today

**Comment by florianrusch-zf** [comment]
Yes, that was the problem. @wolf4ood thanks again for the hint!
