### ISSUE TITLE
Deprecated validation endpoint

### ISSUE THREAD

**Issue by kilianus777** [eclipse-tractusx/tractusx-edc#909]
## Describe the bug

The memory chart references and creates a validation endpoint and service.
Afaik this endpoint is not available anymore and results in a 404 error during token validation.

### To Reproduce

1. Deploy the default edc memory chart two times
2. Try a data transfer between the two EDCs
3. Fails with 404 by the token transfer endpoint

### Expected behavior

The template of the "normal" chart uses the CONTROL_PATH and CONTROL_PORT instead.
After manually changing the EDC_DATAPLANE_TOKEN_VALIDATION_ENDPOINT to the control endpoint, the transfer succeeds.

## Context Information

- Used version: chart 0.5.3

## Possible Implementation

I guess the fix would be to use the same template as in the "normal" chart.
But I wanted to confirm, before I create a PR.

**Comment by ndr-brt** [comment]
Hey, if you have a PR ready please feel free to open it

**Comment by KilianHaag** [comment]
Hey @ndr-brt, is it possible to reopen the [PR](https://github.com/eclipse-tractusx/tractusx-edc/pull/937) or should I consider this as rejected?

**Comment by ndr-brt** [comment]
re-opened it, it just fell off ignored. I will add reviewers so that won't happen again
