### ISSUE TITLE
One-to-many operands in contract definitions causes a crash when fetching catalog

### ISSUE THREAD

**Issue by johan-lejdung** [eclipse-tractusx/tractusx-edc#915]
## Describe the bug

When an operand that is `one-to-many` friendly ( pretty much anything other than `=`) is used when creating a contractdefinition then you get a 500 error when trying to fetch the catalog. We noticed this when following the following tutorial https://eclipse-tractusx.github.io/docs/tutorials/e2e/boost/provideData.

### To Reproduce

Follow the tutorial at https://eclipse-tractusx.github.io/docs/tutorials/e2e/boost/provideData until step 3. 

1. Do the following command:
```
curl --location 'http://localhost/bob/management/v2/contractdefinitions' \                                                                                                                                      (kind-mxd-tx01/default)
--header 'Content-Type: application/json' \
--header 'X-Api-Key: password' \
--data-raw '{
  "@context": {},
  "@id": "6",
  "@type": "ContractDefinition",
  "accessPolicyId": "31",
  "contractPolicyId": "32",
  "assetsSelector": {
    "@type": "CriterionDto",
    "operandLeft": "https://w3id.org/edc/v0.0.1/ns/id",
    "operator": ">",
    "operandRight": "1"
  }
}'
```
3. Then list the catalog:
```
curl --location 'http://localhost/alice/management/v2/catalog/request' \                                                                                                                                        (kind-mxd-tx01/default)
--header 'Content-Type: application/json' \
--header 'X-Api-Key: password' \
--data-raw '{
    "@context": {},
    "protocol": "dataspace-protocol-http",
    "counterPartyAddress": "http://bob-controlplane:8084/api/v1/dsp",
    "querySpec": {
        "offset": 0,
        "limit": 100
    }
}'
```
5. Scroll down to '....'
6. See error

### Expected behavior

_A clear and concise description of what you expected to happen._

### Screenshots/Error Messages

Error:
```
[{"message":"org.eclipse.edc.spi.http.EdcHttpClientException: Server response to Request{method=POST, url=http://bob-controlplane:8084/api/v1/dsp/catalog/request, headers=[Content-Type:application/json, Authorization:<key_removed>]} was not successful but was 500: <html>\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html;charset=ISO-8859-1\"/>\n<title>Error 500 Internal Server Error</title>\n</head>\n<body><h2>HTTP ERROR 500 Internal Server Error</h2>\n<table>\n<tr><th>URI:</th><td>/api/v1/dsp/catalog/request</td></tr>\n<tr><th>STATUS:</th><td>500</td></tr>\n<tr><th>MESSAGE:</th><td>Internal Server Error</td></tr>\n<tr><th>SERVLET:</th><td>EDC-protocol</td></tr>\n</table>\n<hr/><a href=\"https://eclipse.org/jetty\">Powered by Jetty:// 11.0.15</a><hr/>\n\n</body>\n</html>\n","type":"BadGateway","path":null,"invalidValue":null}]%
```

## Context Information

- OS: Mac OS (M1)

## Possible Implementation

Either provide an error for the user when trying to do something erroneous like this, or implement support for one-to-many contracts perhaps.

**Comment by paullatzelsperger** [comment]
we currently only support "=", "in" and "like"

**Comment by arnoweiss** [comment]
`https://w3id.org/edc/v0.0.1/ns/id` can be any string so it wouldn't really make sense to filter by numerical operands anyway.

**Comment by johan-lejdung** [comment]
Right, makes sense! Perhaps validation should be added though, since it seems it's accepted as an operant but then causes crashes when executed. Without any clear errors for the user

**Comment by ndr-brt** [comment]
we'll do this in the upstream

**Comment by florianrusch-zf** [comment]
Reopend as the implementation is already going on.
