### ISSUE TITLE
Allow regex as operand when assigning policy to asset ( or asset group)

### ISSUE THREAD

**Issue by kianaditya** [eclipse-tractusx/tractusx-edc#916]
## WHAT

Currently, the only "working"operator while assigning policy to asset is "=". It would be much easier to assign a common policy to a "product" asset group that is "tagged" with multiple tags at scale, if we allow a regex operator for defining asset lookup 

(eg. Apply X policy for all products/ product groups that has a tag/one of tags starting/ending with ABC)
(For all products with a tag ending with `2023` and another tag that includes text `customerCategoryQ` apply X policy) 

## WHY
- Current implementation offers a deeply granular way of mapping policies to individual assets ( which is great for full customization for asset <> policy pairing)
- It is not very 'scalability friendly' to keep doing that for say a solution provider that has 500 companies with 500 products each that are transacting with each other across supply chain regularly. 
- It is much more manageable if we have a single well defined policy for a class of suppliers and a class of product.
- Easier to understand what policy is applied to any specific product ( for tracking/logging/debugging etc)

## HOW

// if possible, outlines a solution proposal

## FURTHER NOTES

// anything else you want to outline

_Please be sure to take a look at
our [contribution guidelines](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/CONTRIBUTING.md) and
our [PR etiquette](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/pr_etiquette.md)._

**Comment by jimmarino** [comment]
This issue should be submitted to the upstream EDC repository. However, I don't see how this cannot be easily handled using the current label approach without introducing the complexity of regex.

Create a tag that encompasses the proper grouping and apply it to the desired assets.

**Comment by arnoweiss** [comment]
@kianaditya  - have you tried creating the `contractDefinition` with the `like` operator?
https://github.com/eclipse-edc/Connector/blob/3b70f4f0ca98896d906bffeeb61757545eabe53b/core/common/connector-core/src/main/java/org/eclipse/edc/connector/core/store/CriterionToPredicateConverterImpl.java#L131
