### ISSUE TITLE
Cleanup DAPS references

### ISSUE THREAD

**Issue by ndr-brt** [eclipse-tractusx/tractusx-edc#931]
## WHAT

Currently the repository is full of documentation/modules/tests related to DAPS, but it is not in use anymore since version 0.4.x.
Let's :axe: them.

## WHY
cleanup, avoid confusion

## HOW

// if possible, outlines a solution proposal

## FURTHER NOTES

// anything else you want to outline

_Please be sure to take a look at
our [contribution guidelines](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/CONTRIBUTING.md) and
our [PR etiquette](https://github.com/eclipse-tractusx/tractusx-edc/blob/main/pr_etiquette.md)._

**Comment by wolf4ood** [comment]
:axe:
