### ISSUE TITLE
The Offer must NOT include an explicit target attribute

### ISSUE THREAD

**Issue by matgnt** [eclipse-tractusx/tractusx-edc#935]
I just saw, that our offers contain dataset / target ids, but should not as defined in DSP:
https://github.com/International-Data-Spaces-Association/ids-specification/blob/eadbaa04bbed499eb76207e92e140535a5c367bc/model/model.md?plain=1#L70

We have `odrl:target` in 2 places where it should not appear to my understanding:

Example from the catalog (0.5.1)
```
            "odrl:hasPolicy": [
                {
                    "@id": "NTg4NTUzYTktMDJhNC00MzI3LTg4MzUtMDAxZDg3YzFiOWRl:MjgxNGY4ZjktZWYxYS00YzhkLWIxM2EtZGI1NjUxZjUxNGJi:ODU3MDg5NDAtMjRjOC00NWFiLTg2ZDEtODAzNDIyYzZmMTZh",
                    "@type": "odrl:Set",
                    "odrl:permission": {
                        "odrl:target": "2814f8f9-ef1a-4c8d-b13a-db5651f514bb",
                        "odrl:action": {
                            "odrl:type": "USE"
                        },
                        "odrl:constraint": {
                            "odrl:and": {
                                "odrl:leftOperand": "FrameworkAgreement.membership",
                                "odrl:operator": {
                                    "@id": "odrl:eq"
                                },
                                "odrl:rightOperand": "active"
                            }
                        }
                    },
                    "odrl:prohibition": [],
                    "odrl:obligation": [],
                    "odrl:target": "2814f8f9-ef1a-4c8d-b13a-db5651f514bb"
                },

```

It must only be in the `Agreement` as defined here:
https://github.com/International-Data-Spaces-Association/ids-specification/blob/eadbaa04bbed499eb76207e92e140535a5c367bc/model/model.md?plain=1#L76

--
Matthias Binzer

**Comment by ndr-brt** [comment]
looks like an inconsistency in the specs, because in the `ContractRequestMessage` example that field is valued:
https://github.com/International-Data-Spaces-Association/ids-specification/blob/ca29dbf6e720bf2a1304d6d4fd3dc963a49fcb10/negotiation/message/contract-request-message.json#L7

maybe that should be reported on the ids-specification repository

**Comment by matgnt** [comment]
The updates decided in the spec will require some changes in EDC.

**Comment by ndr-brt** [comment]
all the efforts needed to be compliant with DSP 1.0 are listed in this issue upstream:
https://github.com/eclipse-edc/Connector/issues/3836

**Comment by ndr-brt** [comment]
solved by https://github.com/eclipse-edc/Connector/pull/3868, will be part of the next release
