### ISSUE TITLE
Refactor tests to use context where needed in method args

### ISSUE THREAD

**Issue by wolf4ood** [eclipse-tractusx/tractusx-edc#972]
do we need the `context` at all? we can inject it directly as method arg if needed.

_Originally posted by @paullatzelsperger in https://github.com/eclipse-tractusx/tractusx-edc/pull/968#discussion_r1440244786_

**Comment by rafaelmag110** [comment]
I @wolf4ood, I can help getting this out the way. Can you assign it to me? Thanks
